//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class AccelerationEvent_Wrapper {
        
        private Vector3_Wrapper _acceleration;
        
        private float _deltatime;
        
        public Vector3_Wrapper acceleration {
            get {
                return this._acceleration;
            }
            set {
                this._acceleration = value;
            }
        }
        
        public float deltaTime {
            get {
                return _deltatime;
            }
            set {
                _deltatime = value;
            }
        }
    }
}
