//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class AchievementDescription_Wrapper {
        
        public string id;
        
        public string title;
        
        public Texture2D_Wrapper image;
        
        public string achievedDescription;
        
        public string unachievedDescription;
        
        public bool hidden;
        
        public int points;
    }
}
