//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class AchievementDescription_Wrapper {
        
        private string _id;
        
        private string _title;
        
        private Texture2D_Wrapper _image;
        
        private string _achieveddescription;
        
        private string _unachieveddescription;
        
        private bool _hidden;
        
        private int _points;
        
        public string id {
            get {
                return _id;
            }
            set {
                _id = value;
            }
        }
        
        public string title {
            get {
                return _title;
            }
            set {
                _title = value;
            }
        }
        
        public Texture2D_Wrapper image {
            get {
                return this._image;
            }
            set {
                this._image = value;
            }
        }
        
        public string achievedDescription {
            get {
                return _achieveddescription;
            }
            set {
                _achieveddescription = value;
            }
        }
        
        public string unachievedDescription {
            get {
                return _unachieveddescription;
            }
            set {
                _unachieveddescription = value;
            }
        }
        
        public bool hidden {
            get {
                return _hidden;
            }
            set {
                _hidden = value;
            }
        }
        
        public int points {
            get {
                return _points;
            }
            set {
                _points = value;
            }
        }
    }
}
