//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class AnimationClip_Wrapper {
        
        private float _length;
        
        private float _framerate;
        
        private UnityEngine.WrapMode _wrapmode;
        
        private Bounds_Wrapper _localbounds;
        
        private string _name;
        
        private UnityEngine.HideFlags _hideflags;
        
        public float length {
            get {
                return _length;
            }
            set {
                _length = value;
            }
        }
        
        public float frameRate {
            get {
                return _framerate;
            }
            set {
                _framerate = value;
            }
        }
        
        public UnityEngine.WrapMode wrapMode {
            get {
                return _wrapmode;
            }
            set {
                _wrapmode = value;
            }
        }
        
        public Bounds_Wrapper localBounds {
            get {
                return this._localbounds;
            }
            set {
                this._localbounds = value;
            }
        }
        
        public string name {
            get {
                return _name;
            }
            set {
                _name = value;
            }
        }
        
        public UnityEngine.HideFlags hideFlags {
            get {
                return _hideflags;
            }
            set {
                _hideflags = value;
            }
        }
    }
}
