//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Animator_Wrapper {
        
        private bool _isoptimizable;
        
        private bool _ishuman;
        
        private bool _hasrootmotion;
        
        private float _humanscale;
        
        private Vector3_Wrapper _deltaposition;
        
        private Quaternion_Wrapper _deltarotation;
        
        private Vector3_Wrapper _rootposition;
        
        private Quaternion_Wrapper _rootrotation;
        
        private bool _applyrootmotion;
        
        private bool _animatephysics;
        
        private UnityEngine.AnimatorUpdateMode _updatemode;
        
        private bool _hastransformhierarchy;
        
        private float _gravityweight;
        
        private Vector3_Wrapper _bodyposition;
        
        private Quaternion_Wrapper _bodyrotation;
        
        private bool _stabilizefeet;
        
        private int _layercount;
        
        private float _feetpivotactive;
        
        private float _pivotweight;
        
        private Vector3_Wrapper _pivotposition;
        
        private bool _ismatchingtarget;
        
        private float _speed;
        
        private Vector3_Wrapper _targetposition;
        
        private Quaternion_Wrapper _targetrotation;
        
        private UnityEngine.AnimatorCullingMode _cullingmode;
        
        private float _playbacktime;
        
        private float _recorderstarttime;
        
        private float _recorderstoptime;
        
        private RuntimeAnimatorController_Wrapper _runtimeanimatorcontroller;
        
        private Avatar_Wrapper _avatar;
        
        private bool _layersaffectmasscenter;
        
        private float _leftfeetbottomheight;
        
        private float _rightfeetbottomheight;
        
        private bool _logwarnings;
        
        private bool _fireevents;
        
        private bool _enabled;
        
        private Transform_Wrapper _transform;
        
        private Rigidbody_Wrapper _rigidbody;
        
        private Rigidbody2D_Wrapper _rigidbody2d;
        
        private Camera_Wrapper _camera;
        
        private Light_Wrapper _light;
        
        private Animation_Wrapper _animation;
        
        private ConstantForce_Wrapper _constantforce;
        
        private Renderer_Wrapper _renderer;
        
        private AudioSource_Wrapper _audio;
        
        private GUIText_Wrapper _guitext;
        
        private NetworkView_Wrapper _networkview;
        
        private GUIElement_Wrapper _guielement;
        
        private GUITexture_Wrapper _guitexture;
        
        private Collider_Wrapper _collider;
        
        private Collider2D_Wrapper _collider2d;
        
        private HingeJoint_Wrapper _hingejoint;
        
        private ParticleEmitter_Wrapper _particleemitter;
        
        private ParticleSystem_Wrapper _particlesystem;
        
        private GameObject_Wrapper _gameobject;
        
        private bool _active;
        
        private string _tag;
        
        private string _name;
        
        private UnityEngine.HideFlags _hideflags;
        
        public bool isOptimizable {
            get {
                return _isoptimizable;
            }
            set {
                _isoptimizable = value;
            }
        }
        
        public bool isHuman {
            get {
                return _ishuman;
            }
            set {
                _ishuman = value;
            }
        }
        
        public bool hasRootMotion {
            get {
                return _hasrootmotion;
            }
            set {
                _hasrootmotion = value;
            }
        }
        
        public float humanScale {
            get {
                return _humanscale;
            }
            set {
                _humanscale = value;
            }
        }
        
        public Vector3_Wrapper deltaPosition {
            get {
                return this._deltaposition;
            }
            set {
                this._deltaposition = value;
            }
        }
        
        public Quaternion_Wrapper deltaRotation {
            get {
                return this._deltarotation;
            }
            set {
                this._deltarotation = value;
            }
        }
        
        public Vector3_Wrapper rootPosition {
            get {
                return this._rootposition;
            }
            set {
                this._rootposition = value;
            }
        }
        
        public Quaternion_Wrapper rootRotation {
            get {
                return this._rootrotation;
            }
            set {
                this._rootrotation = value;
            }
        }
        
        public bool applyRootMotion {
            get {
                return _applyrootmotion;
            }
            set {
                _applyrootmotion = value;
            }
        }
        
        public bool animatePhysics {
            get {
                return _animatephysics;
            }
            set {
                _animatephysics = value;
            }
        }
        
        public UnityEngine.AnimatorUpdateMode updateMode {
            get {
                return _updatemode;
            }
            set {
                _updatemode = value;
            }
        }
        
        public bool hasTransformHierarchy {
            get {
                return _hastransformhierarchy;
            }
            set {
                _hastransformhierarchy = value;
            }
        }
        
        public float gravityWeight {
            get {
                return _gravityweight;
            }
            set {
                _gravityweight = value;
            }
        }
        
        public Vector3_Wrapper bodyPosition {
            get {
                return this._bodyposition;
            }
            set {
                this._bodyposition = value;
            }
        }
        
        public Quaternion_Wrapper bodyRotation {
            get {
                return this._bodyrotation;
            }
            set {
                this._bodyrotation = value;
            }
        }
        
        public bool stabilizeFeet {
            get {
                return _stabilizefeet;
            }
            set {
                _stabilizefeet = value;
            }
        }
        
        public int layerCount {
            get {
                return _layercount;
            }
            set {
                _layercount = value;
            }
        }
        
        public float feetPivotActive {
            get {
                return _feetpivotactive;
            }
            set {
                _feetpivotactive = value;
            }
        }
        
        public float pivotWeight {
            get {
                return _pivotweight;
            }
            set {
                _pivotweight = value;
            }
        }
        
        public Vector3_Wrapper pivotPosition {
            get {
                return this._pivotposition;
            }
            set {
                this._pivotposition = value;
            }
        }
        
        public bool isMatchingTarget {
            get {
                return _ismatchingtarget;
            }
            set {
                _ismatchingtarget = value;
            }
        }
        
        public float speed {
            get {
                return _speed;
            }
            set {
                _speed = value;
            }
        }
        
        public Vector3_Wrapper targetPosition {
            get {
                return this._targetposition;
            }
            set {
                this._targetposition = value;
            }
        }
        
        public Quaternion_Wrapper targetRotation {
            get {
                return this._targetrotation;
            }
            set {
                this._targetrotation = value;
            }
        }
        
        public UnityEngine.AnimatorCullingMode cullingMode {
            get {
                return _cullingmode;
            }
            set {
                _cullingmode = value;
            }
        }
        
        public float playbackTime {
            get {
                return _playbacktime;
            }
            set {
                _playbacktime = value;
            }
        }
        
        public float recorderStartTime {
            get {
                return _recorderstarttime;
            }
            set {
                _recorderstarttime = value;
            }
        }
        
        public float recorderStopTime {
            get {
                return _recorderstoptime;
            }
            set {
                _recorderstoptime = value;
            }
        }
        
        public RuntimeAnimatorController_Wrapper runtimeAnimatorController {
            get {
                return this._runtimeanimatorcontroller;
            }
            set {
                this._runtimeanimatorcontroller = value;
            }
        }
        
        public Avatar_Wrapper avatar {
            get {
                return this._avatar;
            }
            set {
                this._avatar = value;
            }
        }
        
        public bool layersAffectMassCenter {
            get {
                return _layersaffectmasscenter;
            }
            set {
                _layersaffectmasscenter = value;
            }
        }
        
        public float leftFeetBottomHeight {
            get {
                return _leftfeetbottomheight;
            }
            set {
                _leftfeetbottomheight = value;
            }
        }
        
        public float rightFeetBottomHeight {
            get {
                return _rightfeetbottomheight;
            }
            set {
                _rightfeetbottomheight = value;
            }
        }
        
        public bool logWarnings {
            get {
                return _logwarnings;
            }
            set {
                _logwarnings = value;
            }
        }
        
        public bool fireEvents {
            get {
                return _fireevents;
            }
            set {
                _fireevents = value;
            }
        }
        
        public bool enabled {
            get {
                return _enabled;
            }
            set {
                _enabled = value;
            }
        }
        
        public Transform_Wrapper transform {
            get {
                return this._transform;
            }
            set {
                this._transform = value;
            }
        }
        
        public Rigidbody_Wrapper rigidbody {
            get {
                return this._rigidbody;
            }
            set {
                this._rigidbody = value;
            }
        }
        
        public Rigidbody2D_Wrapper rigidbody2D {
            get {
                return this._rigidbody2d;
            }
            set {
                this._rigidbody2d = value;
            }
        }
        
        public Camera_Wrapper camera {
            get {
                return this._camera;
            }
            set {
                this._camera = value;
            }
        }
        
        public Light_Wrapper light {
            get {
                return this._light;
            }
            set {
                this._light = value;
            }
        }
        
        public Animation_Wrapper animation {
            get {
                return this._animation;
            }
            set {
                this._animation = value;
            }
        }
        
        public ConstantForce_Wrapper constantForce {
            get {
                return this._constantforce;
            }
            set {
                this._constantforce = value;
            }
        }
        
        public Renderer_Wrapper renderer {
            get {
                return this._renderer;
            }
            set {
                this._renderer = value;
            }
        }
        
        public AudioSource_Wrapper audio {
            get {
                return this._audio;
            }
            set {
                this._audio = value;
            }
        }
        
        public GUIText_Wrapper guiText {
            get {
                return this._guitext;
            }
            set {
                this._guitext = value;
            }
        }
        
        public NetworkView_Wrapper networkView {
            get {
                return this._networkview;
            }
            set {
                this._networkview = value;
            }
        }
        
        public GUIElement_Wrapper guiElement {
            get {
                return this._guielement;
            }
            set {
                this._guielement = value;
            }
        }
        
        public GUITexture_Wrapper guiTexture {
            get {
                return this._guitexture;
            }
            set {
                this._guitexture = value;
            }
        }
        
        public Collider_Wrapper collider {
            get {
                return this._collider;
            }
            set {
                this._collider = value;
            }
        }
        
        public Collider2D_Wrapper collider2D {
            get {
                return this._collider2d;
            }
            set {
                this._collider2d = value;
            }
        }
        
        public HingeJoint_Wrapper hingeJoint {
            get {
                return this._hingejoint;
            }
            set {
                this._hingejoint = value;
            }
        }
        
        public ParticleEmitter_Wrapper particleEmitter {
            get {
                return this._particleemitter;
            }
            set {
                this._particleemitter = value;
            }
        }
        
        public ParticleSystem_Wrapper particleSystem {
            get {
                return this._particlesystem;
            }
            set {
                this._particlesystem = value;
            }
        }
        
        public GameObject_Wrapper gameObject {
            get {
                return this._gameobject;
            }
            set {
                this._gameobject = value;
            }
        }
        
        public bool active {
            get {
                return _active;
            }
            set {
                _active = value;
            }
        }
        
        public string tag {
            get {
                return _tag;
            }
            set {
                _tag = value;
            }
        }
        
        public string name {
            get {
                return _name;
            }
            set {
                _name = value;
            }
        }
        
        public UnityEngine.HideFlags hideFlags {
            get {
                return _hideflags;
            }
            set {
                _hideflags = value;
            }
        }
    }
}
