//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class AnimationState_Wrapper {
        
        private bool _enabled;
        
        private float _weight;
        
        private UnityEngine.WrapMode _wrapmode;
        
        private float _time;
        
        private float _normalizedtime;
        
        private float _speed;
        
        private float _normalizedspeed;
        
        private float _length;
        
        private int _layer;
        
        private AnimationClip_Wrapper _clip;
        
        private string _name;
        
        private UnityEngine.AnimationBlendMode _blendmode;
        
        public bool enabled {
            get {
                return _enabled;
            }
            set {
                _enabled = value;
            }
        }
        
        public float weight {
            get {
                return _weight;
            }
            set {
                _weight = value;
            }
        }
        
        public UnityEngine.WrapMode wrapMode {
            get {
                return _wrapmode;
            }
            set {
                _wrapmode = value;
            }
        }
        
        public float time {
            get {
                return _time;
            }
            set {
                _time = value;
            }
        }
        
        public float normalizedTime {
            get {
                return _normalizedtime;
            }
            set {
                _normalizedtime = value;
            }
        }
        
        public float speed {
            get {
                return _speed;
            }
            set {
                _speed = value;
            }
        }
        
        public float normalizedSpeed {
            get {
                return _normalizedspeed;
            }
            set {
                _normalizedspeed = value;
            }
        }
        
        public float length {
            get {
                return _length;
            }
            set {
                _length = value;
            }
        }
        
        public int layer {
            get {
                return _layer;
            }
            set {
                _layer = value;
            }
        }
        
        public AnimationClip_Wrapper clip {
            get {
                return this._clip;
            }
            set {
                this._clip = value;
            }
        }
        
        public string name {
            get {
                return _name;
            }
            set {
                _name = value;
            }
        }
        
        public UnityEngine.AnimationBlendMode blendMode {
            get {
                return _blendmode;
            }
            set {
                _blendmode = value;
            }
        }
    }
}
