//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class AnimationClip_Wrapper {
        
        public float length;
        
        public float frameRate;
        
        public UnityEngine.WrapMode wrapMode;
        
        public Bounds_Wrapper localBounds;
        
        public string name;
        
        public UnityEngine.HideFlags hideFlags;
    }
}
