//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class AnimatorOverrideController_Wrapper {
        
        public RuntimeAnimatorController_Wrapper runtimeAnimatorController;
        
        public AnimationClip_Wrapper Item;
        
        public UnityEngine.AnimationClipPair[] clips;
        
        public string name;
        
        public UnityEngine.HideFlags hideFlags;
    }
}
