//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class AttachedPathScript_Wrapper {
        
        public TerrainPathCell[] terrainCells;
        
        public bool addNodeMode;
        
        public bool isRoad;
        
        public bool isFinalized;
        
        public PathNodeObjects[] nodeObjects;
        
        public UnityEngine.Vector3[] nodeObjectVerts;
        
        public GameObject_Wrapper pathMesh;
        
        public MeshCollider_Wrapper pathCollider;
        
        public System.Collections.ArrayList pathCells;
        
        public System.Collections.ArrayList totalPathVerts;
        
        public System.Collections.ArrayList innerPathVerts;
        
        public int pathWidth;
        
        public int pathTexture;
        
        public bool pathUniform;
        
        public bool pathFlat;
        
        public bool showHandles;
        
        public float pathWear;
        
        public int pathSmooth;
        
        public GameObject_Wrapper parentTerrain;
        
        public GameObject_Wrapper terrainObj;
        
        public Terrain_Wrapper terComponent;
        
        public TerrainData_Wrapper terData;
        
        public TerrainCollider_Wrapper terrainCollider;
        
        public float[,] terrainHeights;
        
        public bool useGUILayout;
        
        public bool enabled;
        
        public Transform_Wrapper transform;
        
        public Rigidbody_Wrapper rigidbody;
        
        public Rigidbody2D_Wrapper rigidbody2D;
        
        public Camera_Wrapper camera;
        
        public Light_Wrapper light;
        
        public Animation_Wrapper animation;
        
        public ConstantForce_Wrapper constantForce;
        
        public Renderer_Wrapper renderer;
        
        public AudioSource_Wrapper audio;
        
        public GUIText_Wrapper guiText;
        
        public NetworkView_Wrapper networkView;
        
        public GUIElement_Wrapper guiElement;
        
        public GUITexture_Wrapper guiTexture;
        
        public Collider_Wrapper collider;
        
        public Collider2D_Wrapper collider2D;
        
        public HingeJoint_Wrapper hingeJoint;
        
        public ParticleEmitter_Wrapper particleEmitter;
        
        public ParticleSystem_Wrapper particleSystem;
        
        public GameObject_Wrapper gameObject;
        
        public bool active;
        
        public string tag;
        
        public string name;
        
        public UnityEngine.HideFlags hideFlags;
    }
}
