//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    [SocketCommon.Attributes.InstanceNameAttribute("audio")]
    public class AudioSource_Wrapper {
        
        public float volume;
        
        public float pitch;
        
        public float time;
        
        public int timeSamples;
        
        public AudioClip_Wrapper clip;
        
        public bool isPlaying;
        
        public bool loop;
        
        public bool ignoreListenerVolume;
        
        public bool playOnAwake;
        
        public bool ignoreListenerPause;
        
        public UnityEngine.AudioVelocityUpdateMode velocityUpdateMode;
        
        public float panLevel;
        
        public bool bypassEffects;
        
        public bool bypassListenerEffects;
        
        public bool bypassReverbZones;
        
        public float dopplerLevel;
        
        public float spread;
        
        public int priority;
        
        public bool mute;
        
        public float minDistance;
        
        public float maxDistance;
        
        public float pan;
        
        public UnityEngine.AudioRolloffMode rolloffMode;
        
        public float minVolume;
        
        public float maxVolume;
        
        public float rolloffFactor;
        
        public bool enabled;
        
        public Transform_Wrapper transform;
        
        public Rigidbody_Wrapper rigidbody;
        
        public Rigidbody2D_Wrapper rigidbody2D;
        
        public Camera_Wrapper camera;
        
        public Light_Wrapper light;
        
        public Animation_Wrapper animation;
        
        public ConstantForce_Wrapper constantForce;
        
        public Renderer_Wrapper renderer;
        
        public AudioSource_Wrapper audio;
        
        public GUIText_Wrapper guiText;
        
        public NetworkView_Wrapper networkView;
        
        public GUIElement_Wrapper guiElement;
        
        public GUITexture_Wrapper guiTexture;
        
        public Collider_Wrapper collider;
        
        public Collider2D_Wrapper collider2D;
        
        public HingeJoint_Wrapper hingeJoint;
        
        public ParticleEmitter_Wrapper particleEmitter;
        
        public ParticleSystem_Wrapper particleSystem;
        
        public GameObject_Wrapper gameObject;
        
        public bool active;
        
        public string tag;
        
        public string name;
        
        public UnityEngine.HideFlags hideFlags;
    }
}
