//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class AudioReverbFilter_Wrapper {
        
        private UnityEngine.AudioReverbPreset _reverbpreset;
        
        private float _drylevel;
        
        private float _room;
        
        private float _roomhf;
        
        private float _roomrolloff;
        
        private float _decaytime;
        
        private float _decayhfratio;
        
        private float _reflectionslevel;
        
        private float _reflectionsdelay;
        
        private float _reverblevel;
        
        private float _reverbdelay;
        
        private float _diffusion;
        
        private float _density;
        
        private float _hfreference;
        
        private float _roomlf;
        
        private float _lfreference;
        
        private bool _enabled;
        
        private Transform_Wrapper _transform;
        
        private Rigidbody_Wrapper _rigidbody;
        
        private Rigidbody2D_Wrapper _rigidbody2d;
        
        private Camera_Wrapper _camera;
        
        private Light_Wrapper _light;
        
        private Animation_Wrapper _animation;
        
        private ConstantForce_Wrapper _constantforce;
        
        private Renderer_Wrapper _renderer;
        
        private AudioSource_Wrapper _audio;
        
        private GUIText_Wrapper _guitext;
        
        private NetworkView_Wrapper _networkview;
        
        private GUIElement_Wrapper _guielement;
        
        private GUITexture_Wrapper _guitexture;
        
        private Collider_Wrapper _collider;
        
        private Collider2D_Wrapper _collider2d;
        
        private HingeJoint_Wrapper _hingejoint;
        
        private ParticleEmitter_Wrapper _particleemitter;
        
        private ParticleSystem_Wrapper _particlesystem;
        
        private GameObject_Wrapper _gameobject;
        
        private bool _active;
        
        private string _tag;
        
        private string _name;
        
        private UnityEngine.HideFlags _hideflags;
        
        public UnityEngine.AudioReverbPreset reverbPreset {
            get {
                return _reverbpreset;
            }
            set {
                _reverbpreset = value;
            }
        }
        
        public float dryLevel {
            get {
                return _drylevel;
            }
            set {
                _drylevel = value;
            }
        }
        
        public float room {
            get {
                return _room;
            }
            set {
                _room = value;
            }
        }
        
        public float roomHF {
            get {
                return _roomhf;
            }
            set {
                _roomhf = value;
            }
        }
        
        public float roomRolloff {
            get {
                return _roomrolloff;
            }
            set {
                _roomrolloff = value;
            }
        }
        
        public float decayTime {
            get {
                return _decaytime;
            }
            set {
                _decaytime = value;
            }
        }
        
        public float decayHFRatio {
            get {
                return _decayhfratio;
            }
            set {
                _decayhfratio = value;
            }
        }
        
        public float reflectionsLevel {
            get {
                return _reflectionslevel;
            }
            set {
                _reflectionslevel = value;
            }
        }
        
        public float reflectionsDelay {
            get {
                return _reflectionsdelay;
            }
            set {
                _reflectionsdelay = value;
            }
        }
        
        public float reverbLevel {
            get {
                return _reverblevel;
            }
            set {
                _reverblevel = value;
            }
        }
        
        public float reverbDelay {
            get {
                return _reverbdelay;
            }
            set {
                _reverbdelay = value;
            }
        }
        
        public float diffusion {
            get {
                return _diffusion;
            }
            set {
                _diffusion = value;
            }
        }
        
        public float density {
            get {
                return _density;
            }
            set {
                _density = value;
            }
        }
        
        public float hfReference {
            get {
                return _hfreference;
            }
            set {
                _hfreference = value;
            }
        }
        
        public float roomLF {
            get {
                return _roomlf;
            }
            set {
                _roomlf = value;
            }
        }
        
        public float lFReference {
            get {
                return _lfreference;
            }
            set {
                _lfreference = value;
            }
        }
        
        public bool enabled {
            get {
                return _enabled;
            }
            set {
                _enabled = value;
            }
        }
        
        public Transform_Wrapper transform {
            get {
                return this._transform;
            }
            set {
                this._transform = value;
            }
        }
        
        public Rigidbody_Wrapper rigidbody {
            get {
                return this._rigidbody;
            }
            set {
                this._rigidbody = value;
            }
        }
        
        public Rigidbody2D_Wrapper rigidbody2D {
            get {
                return this._rigidbody2d;
            }
            set {
                this._rigidbody2d = value;
            }
        }
        
        public Camera_Wrapper camera {
            get {
                return this._camera;
            }
            set {
                this._camera = value;
            }
        }
        
        public Light_Wrapper light {
            get {
                return this._light;
            }
            set {
                this._light = value;
            }
        }
        
        public Animation_Wrapper animation {
            get {
                return this._animation;
            }
            set {
                this._animation = value;
            }
        }
        
        public ConstantForce_Wrapper constantForce {
            get {
                return this._constantforce;
            }
            set {
                this._constantforce = value;
            }
        }
        
        public Renderer_Wrapper renderer {
            get {
                return this._renderer;
            }
            set {
                this._renderer = value;
            }
        }
        
        public AudioSource_Wrapper audio {
            get {
                return this._audio;
            }
            set {
                this._audio = value;
            }
        }
        
        public GUIText_Wrapper guiText {
            get {
                return this._guitext;
            }
            set {
                this._guitext = value;
            }
        }
        
        public NetworkView_Wrapper networkView {
            get {
                return this._networkview;
            }
            set {
                this._networkview = value;
            }
        }
        
        public GUIElement_Wrapper guiElement {
            get {
                return this._guielement;
            }
            set {
                this._guielement = value;
            }
        }
        
        public GUITexture_Wrapper guiTexture {
            get {
                return this._guitexture;
            }
            set {
                this._guitexture = value;
            }
        }
        
        public Collider_Wrapper collider {
            get {
                return this._collider;
            }
            set {
                this._collider = value;
            }
        }
        
        public Collider2D_Wrapper collider2D {
            get {
                return this._collider2d;
            }
            set {
                this._collider2d = value;
            }
        }
        
        public HingeJoint_Wrapper hingeJoint {
            get {
                return this._hingejoint;
            }
            set {
                this._hingejoint = value;
            }
        }
        
        public ParticleEmitter_Wrapper particleEmitter {
            get {
                return this._particleemitter;
            }
            set {
                this._particleemitter = value;
            }
        }
        
        public ParticleSystem_Wrapper particleSystem {
            get {
                return this._particlesystem;
            }
            set {
                this._particlesystem = value;
            }
        }
        
        public GameObject_Wrapper gameObject {
            get {
                return this._gameobject;
            }
            set {
                this._gameobject = value;
            }
        }
        
        public bool active {
            get {
                return _active;
            }
            set {
                _active = value;
            }
        }
        
        public string tag {
            get {
                return _tag;
            }
            set {
                _tag = value;
            }
        }
        
        public string name {
            get {
                return _name;
            }
            set {
                _name = value;
            }
        }
        
        public UnityEngine.HideFlags hideFlags {
            get {
                return _hideflags;
            }
            set {
                _hideflags = value;
            }
        }
    }
}
