//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class AudioClip_Wrapper {
        
        private float _length;
        
        private int _samples;
        
        private int _channels;
        
        private int _frequency;
        
        private bool _isreadytoplay;
        
        private string _name;
        
        private UnityEngine.HideFlags _hideflags;
        
        public float length {
            get {
                return _length;
            }
            set {
                _length = value;
            }
        }
        
        public int samples {
            get {
                return _samples;
            }
            set {
                _samples = value;
            }
        }
        
        public int channels {
            get {
                return _channels;
            }
            set {
                _channels = value;
            }
        }
        
        public int frequency {
            get {
                return _frequency;
            }
            set {
                _frequency = value;
            }
        }
        
        public bool isReadyToPlay {
            get {
                return _isreadytoplay;
            }
            set {
                _isreadytoplay = value;
            }
        }
        
        public string name {
            get {
                return _name;
            }
            set {
                _name = value;
            }
        }
        
        public UnityEngine.HideFlags hideFlags {
            get {
                return _hideflags;
            }
            set {
                _hideflags = value;
            }
        }
    }
}
