//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Avatar_Wrapper {
        
        private bool _isvalid;
        
        private bool _ishuman;
        
        private string _name;
        
        private UnityEngine.HideFlags _hideflags;
        
        public bool isValid {
            get {
                return _isvalid;
            }
            set {
                _isvalid = value;
            }
        }
        
        public bool isHuman {
            get {
                return _ishuman;
            }
            set {
                _ishuman = value;
            }
        }
        
        public string name {
            get {
                return _name;
            }
            set {
                _name = value;
            }
        }
        
        public UnityEngine.HideFlags hideFlags {
            get {
                return _hideflags;
            }
            set {
                _hideflags = value;
            }
        }
    }
}
