//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class AxisBinding_Wrapper {
        
        public string idTag;
        
        public string name;
        
        public bool inverted;
        
        public float sensitivity;
        
        public float deadzone;
        
        public float scale;
        
        public float neutralPoint;
        
        public UIModeBindingLinRotState switchState;
        
        public bool useSwitchState;
        
        public ulong inputLockMask;
    }
}
