//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class BaseEvent_Wrapper {
        
        private int _id;
        
        private string _name;
        
        private string _guiname;
        
        public int id {
            get {
                return _id;
            }
            set {
                _id = value;
            }
        }
        
        public string name {
            get {
                return _name;
            }
            set {
                _name = value;
            }
        }
        
        public string GUIName {
            get {
                return _guiname;
            }
            set {
                _guiname = value;
            }
        }
    }
}
