//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class BaseEvent_Wrapper {
        
        public bool active;
        
        public bool guiActive;
        
        public bool guiActiveEditor;
        
        public string guiIcon;
        
        public string guiName;
        
        public string category;
        
        public bool guiActiveUnfocused;
        
        public float unfocusedRange;
        
        public bool externalToEVAOnly;
        
        public BaseEventList_Wrapper listParent;
        
        public bool assigned;
        
        public int id;
        
        public string name;
        
        public string GUIName;
    }
}
