//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class BaseEventList_Wrapper {
        
        private BaseEvent_Wrapper _item;
       
        private int _capacity;
        
        private int _count;
        
        public int Capacity {
            get {
                return _capacity;
            }
            set {
                _capacity = value;
            }
        }
        
        public int Count {
            get {
                return _count;
            }
            set {
                _count = value;
            }
        }
        
        public BaseEvent_Wrapper Item {
            get {
                return this._item;
            }
            set {
                this._item = value;
            }
        }
    }
}
