//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Bounds_Wrapper {
        
        private Vector3_Wrapper _center;
        
        private Vector3_Wrapper _size;
        
        private Vector3_Wrapper _extents;
        
        private Vector3_Wrapper _min;
        
        private Vector3_Wrapper _max;
        
        public Vector3_Wrapper center {
            get {
                return this._center;
            }
            set {
                this._center = value;
            }
        }
        
        public Vector3_Wrapper size {
            get {
                return this._size;
            }
            set {
                this._size = value;
            }
        }
        
        public Vector3_Wrapper extents {
            get {
                return this._extents;
            }
            set {
                this._extents = value;
            }
        }
        
        public Vector3_Wrapper min {
            get {
                return this._min;
            }
            set {
                this._min = value;
            }
        }
        
        public Vector3_Wrapper max {
            get {
                return this._max;
            }
            set {
                this._max = value;
            }
        }
    }
}
