//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class CharacterInfo_Wrapper {
        
        public int index;
        
        public Rect_Wrapper uv;
        
        public Rect_Wrapper vert;
        
        public float width;
        
        public int size;
        
        public UnityEngine.FontStyle style;
        
        public bool flipped;
    }
}
