//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Collision_Wrapper {
        
        private Vector3_Wrapper _relativevelocity;
        
        private Rigidbody_Wrapper _rigidbody;
        
        private Collider_Wrapper _collider;
        
        private Transform_Wrapper _transform;
        
        private GameObject_Wrapper _gameobject;
        
        private UnityEngine.ContactPoint[] _contacts;
        
        private Vector3_Wrapper _impactforcesum;
        
        private Vector3_Wrapper _frictionforcesum;
        
        private Component_Wrapper _other;
        
        public Vector3_Wrapper relativeVelocity {
            get {
                return this._relativevelocity;
            }
            set {
                this._relativevelocity = value;
            }
        }
        
        public Rigidbody_Wrapper rigidbody {
            get {
                return this._rigidbody;
            }
            set {
                this._rigidbody = value;
            }
        }
        
        public Collider_Wrapper collider {
            get {
                return this._collider;
            }
            set {
                this._collider = value;
            }
        }
        
        public Transform_Wrapper transform {
            get {
                return this._transform;
            }
            set {
                this._transform = value;
            }
        }
        
        public GameObject_Wrapper gameObject {
            get {
                return this._gameobject;
            }
            set {
                this._gameobject = value;
            }
        }
        
        public UnityEngine.ContactPoint[] contacts {
            get {
                return _contacts;
            }
            set {
                _contacts = value;
            }
        }
        
        public Vector3_Wrapper impactForceSum {
            get {
                return this._impactforcesum;
            }
            set {
                this._impactforcesum = value;
            }
        }
        
        public Vector3_Wrapper frictionForceSum {
            get {
                return this._frictionforcesum;
            }
            set {
                this._frictionforcesum = value;
            }
        }
        
        public Component_Wrapper other {
            get {
                return this._other;
            }
            set {
                this._other = value;
            }
        }
    }
}
