//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Collision2D_Wrapper {
        
        private Rigidbody2D_Wrapper _rigidbody;
        
        private Collider2D_Wrapper _collider;
        
        private Transform_Wrapper _transform;
        
        private GameObject_Wrapper _gameobject;
        
        private UnityEngine.ContactPoint2D[] _contacts;
        
        private Vector2_Wrapper _relativevelocity;
        
        public Rigidbody2D_Wrapper rigidbody {
            get {
                return this._rigidbody;
            }
            set {
                this._rigidbody = value;
            }
        }
        
        public Collider2D_Wrapper collider {
            get {
                return this._collider;
            }
            set {
                this._collider = value;
            }
        }
        
        public Transform_Wrapper transform {
            get {
                return this._transform;
            }
            set {
                this._transform = value;
            }
        }
        
        public GameObject_Wrapper gameObject {
            get {
                return this._gameobject;
            }
            set {
                this._gameobject = value;
            }
        }
        
        public UnityEngine.ContactPoint2D[] contacts {
            get {
                return _contacts;
            }
            set {
                _contacts = value;
            }
        }
        
        public Vector2_Wrapper relativeVelocity {
            get {
                return this._relativevelocity;
            }
            set {
                this._relativevelocity = value;
            }
        }
    }
}
