//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class CombineInstance_Wrapper {
        
        private Mesh_Wrapper _mesh;
        
        private int _submeshindex;
        
        private Matrix4x4_Wrapper _transform;
        
        public Mesh_Wrapper mesh {
            get {
                return this._mesh;
            }
            set {
                this._mesh = value;
            }
        }
        
        public int subMeshIndex {
            get {
                return _submeshindex;
            }
            set {
                _submeshindex = value;
            }
        }
        
        public Matrix4x4_Wrapper transform {
            get {
                return this._transform;
            }
            set {
                this._transform = value;
            }
        }
    }
}
