//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class ContactPoint2D_Wrapper {
        
        private Vector2_Wrapper _point;
        
        private Vector2_Wrapper _normal;
        
        private Collider2D_Wrapper _collider;
        
        private Collider2D_Wrapper _othercollider;
        
        public Vector2_Wrapper point {
            get {
                return this._point;
            }
            set {
                this._point = value;
            }
        }
        
        public Vector2_Wrapper normal {
            get {
                return this._normal;
            }
            set {
                this._normal = value;
            }
        }
        
        public Collider2D_Wrapper collider {
            get {
                return this._collider;
            }
            set {
                this._collider = value;
            }
        }
        
        public Collider2D_Wrapper otherCollider {
            get {
                return this._othercollider;
            }
            set {
                this._othercollider = value;
            }
        }
    }
}
