//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class CraftBrowser_Wrapper {
        
        public Rect_Wrapper windowRect;
        
        public string windowTitle;
        
        public Texture2D_Wrapper FileIcon;
        
        public UnityEngine.GUISkin skin;
        
        public string craftSubfolder;
        
        public string profileName;
        
        public CraftBrowser.SelectedCallback OnFileSelected;
        
        public CraftBrowser.CancelledCallback OnBrowseCancelled;
        
        public string flagURL;
    }
}
