//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Curve_Wrapper {
        
        private int _controlpointcount;
        
        private System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<double, double>> _controlpoints;
        
        private ModuleBase_Wrapper _item;
        
        private int _sourcemodulecount;
        
        private bool _isdisposed;
        
        public int ControlPointCount {
            get {
                return _controlpointcount;
            }
            set {
                _controlpointcount = value;
            }
        }
        
        public System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<double, double>> ControlPoints {
            get {
                return _controlpoints;
            }
            set {
                _controlpoints = value;
            }
        }
        
        public ModuleBase_Wrapper Item {
            get {
                return this._item;
            }
            set {
                this._item = value;
            }
        }
        
        public int SourceModuleCount {
            get {
                return _sourcemodulecount;
            }
            set {
                _sourcemodulecount = value;
            }
        }
        
        public bool IsDisposed {
            get {
                return _isdisposed;
            }
            set {
                _isdisposed = value;
            }
        }
    }
}
