//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class DetonatorSpray_Wrapper {
        
        public GameObject_Wrapper sprayObject;
        
        public int count;
        
        public float startingRadius;
        
        public float minScale;
        
        public float maxScale;
        
        public bool on;
        
        public bool detonatorControlled;
        
        public float startSize;
        
        public float size;
        
        public float explodeDelayMin;
        
        public float explodeDelayMax;
        
        public float startDuration;
        
        public float duration;
        
        public float timeScale;
        
        public float startDetail;
        
        public float detail;
        
        public Color_Wrapper startColor;
        
        public Color_Wrapper color;
        
        public Vector3_Wrapper startLocalPosition;
        
        public Vector3_Wrapper localPosition;
        
        public Vector3_Wrapper startForce;
        
        public Vector3_Wrapper force;
        
        public Vector3_Wrapper startVelocity;
        
        public Vector3_Wrapper velocity;
        
        public float detailThreshold;
        
        public bool useGUILayout;
        
        public bool enabled;
        
        public Transform_Wrapper transform;
        
        public Rigidbody_Wrapper rigidbody;
        
        public Rigidbody2D_Wrapper rigidbody2D;
        
        public Camera_Wrapper camera;
        
        public Light_Wrapper light;
        
        public Animation_Wrapper animation;
        
        public ConstantForce_Wrapper constantForce;
        
        public Renderer_Wrapper renderer;
        
        public AudioSource_Wrapper audio;
        
        public GUIText_Wrapper guiText;
        
        public NetworkView_Wrapper networkView;
        
        public GUIElement_Wrapper guiElement;
        
        public GUITexture_Wrapper guiTexture;
        
        public Collider_Wrapper collider;
        
        public Collider2D_Wrapper collider2D;
        
        public HingeJoint_Wrapper hingeJoint;
        
        public ParticleEmitter_Wrapper particleEmitter;
        
        public ParticleSystem_Wrapper particleSystem;
        
        public GameObject_Wrapper gameObject;
        
        public bool active;
        
        public string tag;
        
        public string name;
        
        public UnityEngine.HideFlags hideFlags;
    }
}
