//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Display_Wrapper {
        
        public UnityEngine.Display[] _displays_wrapped;
        
        private int _renderingwidth;
        
        private int _renderingheight;
        
        private int _systemwidth;
        
        private int _systemheight;
        
        private RenderBuffer_Wrapper _colorbuffer;
        
        private RenderBuffer_Wrapper _depthbuffer;
        
        public int renderingWidth {
            get {
                return _renderingwidth;
            }
            set {
                _renderingwidth = value;
            }
        }
        
        public int renderingHeight {
            get {
                return _renderingheight;
            }
            set {
                _renderingheight = value;
            }
        }
        
        public int systemWidth {
            get {
                return _systemwidth;
            }
            set {
                _systemwidth = value;
            }
        }
        
        public int systemHeight {
            get {
                return _systemheight;
            }
            set {
                _systemheight = value;
            }
        }
        
        public RenderBuffer_Wrapper colorBuffer {
            get {
                return this._colorbuffer;
            }
            set {
                this._colorbuffer = value;
            }
        }
        
        public RenderBuffer_Wrapper depthBuffer {
            get {
                return this._depthbuffer;
            }
            set {
                this._depthbuffer = value;
            }
        }
    }
}
