//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class DynamicPlanetSphere_Wrapper {
        
        public Texture2D_Wrapper heightMap;
        
        public Texture2D_Wrapper detailMap;
        
        public float detailMapScale;
        
        public float detailMapHeight;
        
        public Material_Wrapper material;
        
        public float innerRadius;
        
        public float outerRadius;
        
        public float heightOffset;
        
        public Transform_Wrapper patchFocus;
        
        public int xRes;
        
        public int yRes;
        
        public float textureScale;
        
        public bool textureIsHeightField;
        
        public float updateOffsetThreshold;
        
        public bool drawGizmos;
        
        public bool degub;
        
        public bool showBlendMap;
        
        public Color_Wrapper fallbackColor;
        
        public DynamicOceanSphere_Wrapper ocean;
        
        public float heightFieldOffsetU;
        
        public float heightFieldOffsetV;
        
        public Mesh_Wrapper mesh;
        
        public Vector3_Wrapper gridCenter;
        
        public float gridAngle;
        
        public float latitude;
        
        public float longitude;
        
        public float latStart;
        
        public float latEnd;
        
        public float longStart;
        
        public float longEnd;
        
        public float angularQuantization;
        
        public bool gridDirty;
        
        public float runTimeLimit;
        
        public bool useGUILayout;
        
        public bool enabled;
        
        public Transform_Wrapper transform;
        
        public Rigidbody_Wrapper rigidbody;
        
        public Rigidbody2D_Wrapper rigidbody2D;
        
        public Camera_Wrapper camera;
        
        public Light_Wrapper light;
        
        public Animation_Wrapper animation;
        
        public ConstantForce_Wrapper constantForce;
        
        public Renderer_Wrapper renderer;
        
        public AudioSource_Wrapper audio;
        
        public GUIText_Wrapper guiText;
        
        public NetworkView_Wrapper networkView;
        
        public GUIElement_Wrapper guiElement;
        
        public GUITexture_Wrapper guiTexture;
        
        public Collider_Wrapper collider;
        
        public Collider2D_Wrapper collider2D;
        
        public HingeJoint_Wrapper hingeJoint;
        
        public ParticleEmitter_Wrapper particleEmitter;
        
        public ParticleSystem_Wrapper particleSystem;
        
        public GameObject_Wrapper gameObject;
        
        public bool active;
        
        public string tag;
        
        public string name;
        
        public UnityEngine.HideFlags hideFlags;
    }
}
