//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class EditorStartPodDialog_Wrapper {
        
        public Vector3_Wrapper partListScenePos;
        
        public Vector2_Wrapper partListSceneBounds;
        
        public float iconSpacing;
        
        public PartListCategory_Wrapper podList;
        
        public RenderTexture_Wrapper listTexture;
        
        public Camera_Wrapper podListCamera;
        
        public UnityEngine.GUISkin dialogSkin;
        
        public UnityEngine.GUISkin shipBrowserSkin;
        
        public GameObject_Wrapper selectionQuad;
        
        public GameObject_Wrapper highlightQuad;
        
        public System.Collections.Generic.List<AvailablePart> availablePods;
        
        public AvailablePart selectedPod;
        
        public bool drawDialog;
        
        public EditorStartPodDialog.PodSelectCallback OnPodSelect;
        
        public Callback OnLoadSelect;
        
        public bool Enabled;
        
        public System.Collections.Generic.List<UnityEngine.GameObject> Icons;
        
        public Camera_Wrapper listCamera;
        
        public Vector2_Wrapper ListMousePos;
        
        public bool useGUILayout;
        
        public bool enabled;
        
        public Transform_Wrapper transform;
        
        public Rigidbody_Wrapper rigidbody;
        
        public Rigidbody2D_Wrapper rigidbody2D;
        
        public Camera_Wrapper camera;
        
        public Light_Wrapper light;
        
        public Animation_Wrapper animation;
        
        public ConstantForce_Wrapper constantForce;
        
        public Renderer_Wrapper renderer;
        
        public AudioSource_Wrapper audio;
        
        public GUIText_Wrapper guiText;
        
        public NetworkView_Wrapper networkView;
        
        public GUIElement_Wrapper guiElement;
        
        public GUITexture_Wrapper guiTexture;
        
        public Collider_Wrapper collider;
        
        public Collider2D_Wrapper collider2D;
        
        public HingeJoint_Wrapper hingeJoint;
        
        public ParticleEmitter_Wrapper particleEmitter;
        
        public ParticleSystem_Wrapper particleSystem;
        
        public GameObject_Wrapper gameObject;
        
        public bool active;
        
        public string tag;
        
        public string name;
        
        public UnityEngine.HideFlags hideFlags;
    }
}
