//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class EditorPartListFilter_Wrapper {
        
        private System.Func<AvailablePart, bool> _filtercriteria;
        
        private string _id;
        
        public System.Func<AvailablePart, bool> FilterCriteria {
            get {
                return _filtercriteria;
            }
            set {
                _filtercriteria = value;
            }
        }
        
        public string ID {
            get {
                return _id;
            }
            set {
                _id = value;
            }
        }
    }
}
