//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class ExitGUIException_Wrapper {
        
        private string _message;
        
        private System.Collections.IDictionary _data;
        
        private System.Exception _innerexception;
        
        private System.Reflection.MethodBase _targetsite;
        
        private string _stacktrace;
        
        private string _helplink;
        
        private string _source;
        
        private int _hresult;
        
        public string Message {
            get {
                return _message;
            }
            set {
                _message = value;
            }
        }
        
        public System.Collections.IDictionary Data {
            get {
                return _data;
            }
            set {
                _data = value;
            }
        }
        
        public System.Exception InnerException {
            get {
                return _innerexception;
            }
            set {
                _innerexception = value;
            }
        }
        
        public System.Reflection.MethodBase TargetSite {
            get {
                return _targetsite;
            }
            set {
                _targetsite = value;
            }
        }
        
        public string StackTrace {
            get {
                return _stacktrace;
            }
            set {
                _stacktrace = value;
            }
        }
        
        public string HelpLink {
            get {
                return _helplink;
            }
            set {
                _helplink = value;
            }
        }
        
        public string Source {
            get {
                return _source;
            }
            set {
                _source = value;
            }
        }
        
        public int HResult {
            get {
                return _hresult;
            }
            set {
                _hresult = value;
            }
        }
    }
}
