//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class FileInfo_Wrapper {
        
        private string _name;
        
        private long _length;
        
        private string _directoryname;
        
        private bool _isreadonly;
        
        private bool _exists;
        
        public string Name {
            get {
                return _name;
            }
            set {
                _name = value;
            }
        }
        
        public long Length {
            get {
                return _length;
            }
            set {
                _length = value;
            }
        }
        
        public string DirectoryName {
            get {
                return _directoryname;
            }
            set {
                _directoryname = value;
            }
        }
        
        public bool IsReadOnly {
            get {
                return _isreadonly;
            }
            set {
                _isreadonly = value;
            }
        }
        
        public bool Exists {
            get {
                return _exists;
            }
            set {
                _exists = value;
            }
        }
    }
}
