//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class FileStream_Wrapper {
        
        public string Name;
        
        public long Length;
        
        public bool IsAsync;
        
        public bool CanRead;
        
        public bool CanSeek;
        
        public bool CanWrite;
        
        public long Position;
    }
}
