//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class FileBrowser_Wrapper {
        
        public bool disallowDirectoryChange;
        
        public bool hideFileExtensions;
        
        public string CurrentDirectory;
        
        public string SelectionPattern;
        
        public Texture2D_Wrapper DirectoryImage;
        
        public Texture2D_Wrapper FileImage;
        
        public FileBrowserType BrowserType;
    }
}
