//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class FlightCtrlState_Wrapper {
        
        public float mainThrottle;
        
        public float fastThrottle;
        
        public float roll;
        
        public float yaw;
        
        public float pitch;
        
        public float rollTrim;
        
        public float yawTrim;
        
        public float pitchTrim;
        
        public float wheelSteer;
        
        public float wheelSteerTrim;
        
        public float wheelThrottle;
        
        public float wheelThrottleTrim;
        
        public float X;
        
        public float Y;
        
        public float Z;
        
        public bool killRot;
        
        public bool gearUp;
        
        public bool gearDown;
        
        public bool headlight;
        
        public bool isNeutral;
    }
}
