//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    [SocketCommon.Attributes.InstanceNameAttribute("Instance")]
    public class FlightUIModeController_Wrapper {
        
        public ScreenSafeUIStateButton_Wrapper stagingButton;
        
        public ScreenSafeUIStateButton_Wrapper dockingButton;
        
        public ScreenSafeUIStateButton_Wrapper orbitalButton;
        
        public ScreenSafeUISlideTab_Wrapper altimeterFrame;
        
        public ScreenSafeUISlideTab_Wrapper timeFrame;
        
        public ScreenSafeUISlideTab_Wrapper MapOptionsQuadrant;
        
        public ScreenSafeUISlideTab_Wrapper stagingQuadrant;
        
        public ScreenSafeUISlideTab_Wrapper dockingRotQuadrant;
        
        public ScreenSafeUISlideTab_Wrapper dockingLinQuadrant;
        
        public ScreenSafeUISlideTab_Wrapper crew;
        
        public ScreenSafeUISlideTab_Wrapper navBall;
        
        public ScreenSafeUIMultiStateSlideTab_Wrapper uiModeFrame;
        
        public UIModePanelState[] UIPanelStates;
        
        public FlightUIModeController_Wrapper Instance;
        
        public FlightUIMode Mode;
        
        public bool useGUILayout;
        
        public bool enabled;
        
        public Transform_Wrapper transform;
        
        public Rigidbody_Wrapper rigidbody;
        
        public Rigidbody2D_Wrapper rigidbody2D;
        
        public Camera_Wrapper camera;
        
        public Light_Wrapper light;
        
        public Animation_Wrapper animation;
        
        public ConstantForce_Wrapper constantForce;
        
        public Renderer_Wrapper renderer;
        
        public AudioSource_Wrapper audio;
        
        public GUIText_Wrapper guiText;
        
        public NetworkView_Wrapper networkView;
        
        public GUIElement_Wrapper guiElement;
        
        public GUITexture_Wrapper guiTexture;
        
        public Collider_Wrapper collider;
        
        public Collider2D_Wrapper collider2D;
        
        public HingeJoint_Wrapper hingeJoint;
        
        public ParticleEmitter_Wrapper particleEmitter;
        
        public ParticleSystem_Wrapper particleSystem;
        
        public GameObject_Wrapper gameObject;
        
        public bool active;
        
        public string tag;
        
        public string name;
        
        public UnityEngine.HideFlags hideFlags;
    }
}
