//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Font_Wrapper {
        
        public Material_Wrapper material;
        
        public string[] fontNames;
        
        public UnityEngine.CharacterInfo[] characterInfo;
        
        public UnityEngine.Font.FontTextureRebuildCallback textureRebuildCallback;
        
        public bool dynamic;
        
        public string name;
        
        public UnityEngine.HideFlags hideFlags;
    }
}
