//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class GameCenterPlatform_Wrapper {
        
        private UnityEngine.SocialPlatforms.ILocalUser _localuser;
        
        public UnityEngine.SocialPlatforms.ILocalUser localUser {
            get {
                return _localuser;
            }
            set {
                _localuser = value;
            }
        }
    }
}
