//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Game_Wrapper {
        
        public int _lastCompatibleMajor_wrapped;
        
        public int _lastCompatibleMinor_wrapped;
        
        public int _lastCompatibleRev_wrapped;
        
        private double _universaltime;
        
        public double UniversalTime {
            get {
                return _universaltime;
            }
            set {
                _universaltime = value;
            }
        }
    }
}
