//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class GameSettings_Wrapper {
        
        public string configFilePath;
        
        public string launcherFilePath;
        
        public bool overrideSettings;
        
        public string SETTINGS_FILE_VERSION;
        
        public bool TUTORIALS_EDITOR_ENABLE;
        
        public bool TUTORIALS_FLIGHT_ENABLE;
        
        public bool VAB_USE_CLICK_PLACE;
        
        public bool VAB_USE_ANGLE_SNAP;
        
        public bool VAB_ANGLE_SNAP_INCLUDE_VERTICAL;
        
        public float VAB_CAMERA_ORBIT_SENS;
        
        public float VAB_CAMERA_ZOOM_SENS;
        
        public float FLT_CAMERA_ORBIT_SENS;
        
        public float FLT_CAMERA_ZOOM_SENS;
        
        public float FLT_CAMERA_WOBBLE;
        
        public float FLT_CAMERA_CHASE_SHARPNESS;
        
        public bool FLT_CAMERA_CHASE_USEVELOCITYVECTOR;
        
        public bool FLT_VESSEL_LABELS;
        
        public float SPACENAV_CAMERA_SENS_ROT;
        
        public float SPACENAV_CAMERA_SENS_LIN;
        
        public float SPACENAV_CAMERA_SHARPNESS_LIN;
        
        public float SPACENAV_CAMERA_SHARPNESS_ROT;
        
        public bool SIMULATE_IN_BACKGROUND;
        
        public float PHYSICS_FRAME_DT_LIMIT;
        
        public int MAX_VESSELS_BUDGET;
        
        public int CONIC_PATCH_DRAW_MODE;
        
        public int CONIC_PATCH_LIMIT;
        
        public bool SHOW_PWARP_WARNING;
        
        public bool EVA_ROTATE_ON_MOVE;
        
        public bool USE_STAGING_CONTROLS_ON_DOCKING;
        
        public float SPACENAV_FLIGHT_SENS_ROT;
        
        public float SPACENAV_FLIGHT_SENS_LIN;
        
        public bool KERBIN_TIME;
        
        public bool CALL_HOME;
        
        public bool DONT_SEND_IP;
        
        public bool SEND_PROGRESS_DATA;
        
        public bool CHECK_FOR_UPDATES;
        
        public bool VERBOSE_DEBUG_LOG;
        
        public bool SHOW_CONSOLE_ON_ERROR;
        
        public float AUTOSAVE_INTERVAL;
        
        public float AUTOSAVE_SHORT_INTERVAL;
        
        public bool SHOW_SPACE_CENTER_CREW;
        
        public int UI_SIZE;
        
        public float SHIP_VOLUME;
        
        public float AMBIENCE_VOLUME;
        
        public float MUSIC_VOLUME;
        
        public float UI_VOLUME;
        
        public float VOICE_VOLUME;
        
        public bool SOUND_NORMALIZER_ENABLED;
        
        public float SOUND_NORMALIZER_THRESHOLD;
        
        public float SOUND_NORMALIZER_RESPONSIVENESS;
        
        public int SOUND_NORMALIZER_SKIPSAMPLES;
        
        public int SCREEN_RESOLUTION_WIDTH;
        
        public int SCREEN_RESOLUTION_HEIGHT;
        
        public bool FULLSCREEN;
        
        public int QUALITY_PRESET;
        
        public int ANTI_ALIASING;
        
        public int TEXTURE_QUALITY;
        
        public int SYNC_VBL;
        
        public int LIGHT_QUALITY;
        
        public int SHADOWS_QUALITY;
        
        public int FRAMERATE_LIMIT;
        
        public bool FALLBACK_PART_SHADERS;
        
        public bool PLANET_FORCE_SHADER_MODEL_2_0;
        
        public bool PLANET_SCATTER;
        
        public float PLANET_SCATTER_FACTOR;
        
        public int AERO_FX_QUALITY;
        
        public float INPUT_KEYBOARD_SENSIVITITY;
        
        public KeyBinding_Wrapper PITCH_DOWN;
        
        public KeyBinding_Wrapper PITCH_UP;
        
        public KeyBinding_Wrapper YAW_LEFT;
        
        public KeyBinding_Wrapper YAW_RIGHT;
        
        public KeyBinding_Wrapper ROLL_LEFT;
        
        public KeyBinding_Wrapper ROLL_RIGHT;
        
        public KeyBinding_Wrapper THROTTLE_UP;
        
        public KeyBinding_Wrapper THROTTLE_DOWN;
        
        public KeyBinding_Wrapper SAS_HOLD;
        
        public KeyBinding_Wrapper SAS_TOGGLE;
        
        public KeyBinding_Wrapper LAUNCH_STAGES;
        
        public KeyBinding_Wrapper CAMERA_MODE;
        
        public KeyBinding_Wrapper CAMERA_NEXT;
        
        public KeyBinding_Wrapper PAUSE;
        
        public KeyBinding_Wrapper PRECISION_CTRL;
        
        public KeyBinding_Wrapper ZOOM_IN;
        
        public KeyBinding_Wrapper ZOOM_OUT;
        
        public KeyBinding_Wrapper SCROLL_VIEW_UP;
        
        public KeyBinding_Wrapper SCROLL_VIEW_DOWN;
        
        public KeyBinding_Wrapper SCROLL_ICONS_UP;
        
        public KeyBinding_Wrapper SCROLL_ICONS_DOWN;
        
        public KeyBinding_Wrapper CAMERA_ORBIT_UP;
        
        public KeyBinding_Wrapper CAMERA_ORBIT_DOWN;
        
        public KeyBinding_Wrapper CAMERA_ORBIT_LEFT;
        
        public KeyBinding_Wrapper CAMERA_ORBIT_RIGHT;
        
        public KeyBinding_Wrapper CAMERA_RESET;
        
        public KeyBinding_Wrapper TIME_WARP_INCREASE;
        
        public KeyBinding_Wrapper TIME_WARP_DECREASE;
        
        public KeyBinding_Wrapper MAP_VIEW_TOGGLE;
        
        public KeyBinding_Wrapper UIMODE_STAGING;
        
        public KeyBinding_Wrapper UIMODE_DOCKING;
        
        public KeyBinding_Wrapper TRANSLATE_UP;
        
        public KeyBinding_Wrapper TRANSLATE_DOWN;
        
        public KeyBinding_Wrapper TRANSLATE_LEFT;
        
        public KeyBinding_Wrapper TRANSLATE_RIGHT;
        
        public KeyBinding_Wrapper TRANSLATE_FWD;
        
        public KeyBinding_Wrapper TRANSLATE_BACK;
        
        public KeyBinding_Wrapper RCS_TOGGLE;
        
        public KeyBinding_Wrapper FOCUS_NEXT_VESSEL;
        
        public KeyBinding_Wrapper FOCUS_PREV_VESSEL;
        
        public KeyBinding_Wrapper TOGGLE_UI;
        
        public KeyBinding_Wrapper TOGGLE_STATUS_SCREEN;
        
        public KeyBinding_Wrapper TAKE_SCREENSHOT;
        
        public KeyBinding_Wrapper TOGGLE_LABELS;
        
        public KeyBinding_Wrapper QUICKSAVE;
        
        public KeyBinding_Wrapper QUICKLOAD;
        
        public KeyBinding_Wrapper THROTTLE_CUTOFF;
        
        public KeyBinding_Wrapper LANDING_GEAR;
        
        public KeyBinding_Wrapper HEADLIGHT_TOGGLE;
        
        public KeyBinding_Wrapper BRAKES;
        
        public KeyBinding_Wrapper TOGGLE_SPACENAV_FLIGHT_CONTROL;
        
        public KeyBinding_Wrapper TOGGLE_SPACENAV_ROLL_LOCK;
        
        public KeyBinding_Wrapper EVA_forward;
        
        public KeyBinding_Wrapper EVA_back;
        
        public KeyBinding_Wrapper EVA_left;
        
        public KeyBinding_Wrapper EVA_right;
        
        public KeyBinding_Wrapper EVA_yaw_left;
        
        public KeyBinding_Wrapper EVA_yaw_right;
        
        public KeyBinding_Wrapper EVA_Pack_forward;
        
        public KeyBinding_Wrapper EVA_Pack_back;
        
        public KeyBinding_Wrapper EVA_Pack_left;
        
        public KeyBinding_Wrapper EVA_Pack_right;
        
        public KeyBinding_Wrapper EVA_Pack_up;
        
        public KeyBinding_Wrapper EVA_Pack_down;
        
        public KeyBinding_Wrapper EVA_Jump;
        
        public KeyBinding_Wrapper EVA_Run;
        
        public KeyBinding_Wrapper EVA_ToggleMovementMode;
        
        public KeyBinding_Wrapper EVA_TogglePack;
        
        public KeyBinding_Wrapper EVA_Use;
        
        public KeyBinding_Wrapper EVA_Orient;
        
        public KeyBinding_Wrapper EVA_Lights;
        
        public KeyBinding_Wrapper Docking_pitchUp;
        
        public KeyBinding_Wrapper Docking_pitchDown;
        
        public KeyBinding_Wrapper Docking_yawLeft;
        
        public KeyBinding_Wrapper Docking_yawRight;
        
        public KeyBinding_Wrapper Docking_rollLeft;
        
        public KeyBinding_Wrapper Docking_rollRight;
        
        public KeyBinding_Wrapper Docking_toggleRotLin;
        
        public KeyBinding_Wrapper Docking_staging;
        
        public KeyBinding_Wrapper Docking_linFwd;
        
        public KeyBinding_Wrapper Docking_linBack;
        
        public KeyBinding_Wrapper Docking_linLeft;
        
        public KeyBinding_Wrapper Docking_linRight;
        
        public KeyBinding_Wrapper Docking_linUp;
        
        public KeyBinding_Wrapper Docking_linDown;
        
        public KeyBinding_Wrapper Docking_throttleUp;
        
        public KeyBinding_Wrapper Docking_throttleDown;
        
        public KeyBinding_Wrapper Editor_pitchUp;
        
        public KeyBinding_Wrapper Editor_pitchDown;
        
        public KeyBinding_Wrapper Editor_yawLeft;
        
        public KeyBinding_Wrapper Editor_yawRight;
        
        public KeyBinding_Wrapper Editor_rollLeft;
        
        public KeyBinding_Wrapper Editor_rollRight;
        
        public KeyBinding_Wrapper Editor_resetRotation;
        
        public AxisBinding_Wrapper AXIS_PITCH;
        
        public AxisBinding_Wrapper AXIS_ROLL;
        
        public AxisBinding_Wrapper AXIS_YAW;
        
        public AxisBinding_Wrapper AXIS_THROTTLE;
        
        public AxisBinding_Wrapper AXIS_THROTTLE_INC;
        
        public AxisBinding_Wrapper AXIS_CAMERA_HDG;
        
        public AxisBinding_Wrapper AXIS_CAMERA_PITCH;
        
        public AxisBinding_Wrapper AXIS_TRANSLATE_X;
        
        public AxisBinding_Wrapper AXIS_TRANSLATE_Y;
        
        public AxisBinding_Wrapper AXIS_TRANSLATE_Z;
        
        public AxisBinding_Wrapper AXIS_WHEEL_STEER;
        
        public KeyBinding_Wrapper WHEEL_STEER_LEFT;
        
        public KeyBinding_Wrapper WHEEL_STEER_RIGHT;
        
        public AxisBinding_Wrapper AXIS_WHEEL_THROTTLE;
        
        public KeyBinding_Wrapper WHEEL_THROTTLE_DOWN;
        
        public KeyBinding_Wrapper WHEEL_THROTTLE_UP;
        
        public AxisBinding_Wrapper axis_EVA_translate_x;
        
        public AxisBinding_Wrapper axis_EVA_translate_y;
        
        public AxisBinding_Wrapper axis_EVA_translate_z;
        
        public AxisBinding_Wrapper axis_EVA_pitch;
        
        public AxisBinding_Wrapper axis_EVA_yaw;
        
        public AxisBinding_Wrapper axis_EVA_roll;
        
        public AxisBinding_Wrapper axis_Docking_translate_x;
        
        public AxisBinding_Wrapper axis_Docking_translate_y;
        
        public AxisBinding_Wrapper axis_Docking_translate_z;
        
        public AxisBinding_Wrapper axis_Docking_pitch;
        
        public AxisBinding_Wrapper axis_Docking_yaw;
        
        public AxisBinding_Wrapper axis_Docking_roll;
        
        public AxisBinding_Wrapper axis_Docking_Throttle;
        
        public AxisBinding_Wrapper axis_Docking_Throttle_inc;
        
        public AxisBinding_Wrapper AXIS_MOUSEWHEEL;
        
        public KeyBinding_Wrapper MODIFIER_KEY;
        
        public KeyBinding_Wrapper AbortActionGroup;
        
        public KeyBinding_Wrapper CustomActionGroup1;
        
        public KeyBinding_Wrapper CustomActionGroup2;
        
        public KeyBinding_Wrapper CustomActionGroup3;
        
        public KeyBinding_Wrapper CustomActionGroup4;
        
        public KeyBinding_Wrapper CustomActionGroup5;
        
        public KeyBinding_Wrapper CustomActionGroup6;
        
        public KeyBinding_Wrapper CustomActionGroup7;
        
        public KeyBinding_Wrapper CustomActionGroup8;
        
        public KeyBinding_Wrapper CustomActionGroup9;
        
        public KeyBinding_Wrapper CustomActionGroup10;
        
        public bool dontShowLauncher;
        
        public bool Ready;
        
        public bool useGUILayout;
        
        public bool enabled;
        
        public Transform_Wrapper transform;
        
        public Rigidbody_Wrapper rigidbody;
        
        public Rigidbody2D_Wrapper rigidbody2D;
        
        public Camera_Wrapper camera;
        
        public Light_Wrapper light;
        
        public Animation_Wrapper animation;
        
        public ConstantForce_Wrapper constantForce;
        
        public Renderer_Wrapper renderer;
        
        public AudioSource_Wrapper audio;
        
        public GUIText_Wrapper guiText;
        
        public NetworkView_Wrapper networkView;
        
        public GUIElement_Wrapper guiElement;
        
        public GUITexture_Wrapper guiTexture;
        
        public Collider_Wrapper collider;
        
        public Collider2D_Wrapper collider2D;
        
        public HingeJoint_Wrapper hingeJoint;
        
        public ParticleEmitter_Wrapper particleEmitter;
        
        public ParticleSystem_Wrapper particleSystem;
        
        public GameObject_Wrapper gameObject;
        
        public bool active;
        
        public string tag;
        
        public string name;
        
        public UnityEngine.HideFlags hideFlags;
    }
}
