//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class GenericStack_Wrapper {
        
        private int _count;
        
        private bool _issynchronized;
        
        private object _syncroot;
        
        public int Count {
            get {
                return _count;
            }
            set {
                _count = value;
            }
        }
        
        public bool IsSynchronized {
            get {
                return _issynchronized;
            }
            set {
                _issynchronized = value;
            }
        }
        
        public object SyncRoot {
            get {
                return _syncroot;
            }
            set {
                _syncroot = value;
            }
        }
    }
}
