//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class GL_Wrapper {
        
        public int _TRIANGLES_wrapped;
        
        public int _TRIANGLE_STRIP_wrapped;
        
        public int _QUADS_wrapped;
        
        public int _LINES_wrapped;
    }
}
