//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Gradient_Wrapper {
        
        private UnityEngine.GradientColorKey[] _colorkeys;
        
        private UnityEngine.GradientAlphaKey[] _alphakeys;
        
        public UnityEngine.GradientColorKey[] colorKeys {
            get {
                return _colorkeys;
            }
            set {
                _colorkeys = value;
            }
        }
        
        public UnityEngine.GradientAlphaKey[] alphaKeys {
            get {
                return _alphakeys;
            }
            set {
                _alphakeys = value;
            }
        }
    }
}
