//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class GUIGridSizer_Wrapper {
        
        public float minWidth;
        
        public float maxWidth;
        
        public float minHeight;
        
        public float maxHeight;
        
        public Rect_Wrapper rect;
        
        public int stretchWidth;
        
        public int stretchHeight;
        
        public UnityEngine.GUIStyle style;
        
        public UnityEngine.RectOffset margin;
    }
}
