//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class GUIScrollGroup_Wrapper {
        
        public float calcMinWidth;
        
        public float calcMaxWidth;
        
        public float calcMinHeight;
        
        public float calcMaxHeight;
        
        public float clientWidth;
        
        public float clientHeight;
        
        public bool allowHorizontalScroll;
        
        public bool allowVerticalScroll;
        
        public bool needsHorizontalScrollbar;
        
        public bool needsVerticalScrollbar;
        
        public UnityEngine.GUIStyle horizontalScrollbar;
        
        public UnityEngine.GUIStyle verticalScrollbar;
        
        public bool isVertical;
        
        public bool resetCoords;
        
        public float spacing;
        
        public bool sameSize;
        
        public bool isWindow;
        
        public int windowID;
        
        public float minWidth;
        
        public float maxWidth;
        
        public float minHeight;
        
        public float maxHeight;
        
        public Rect_Wrapper rect;
        
        public int stretchWidth;
        
        public int stretchHeight;
        
        public UnityEngine.RectOffset margin;
        
        public UnityEngine.GUIStyle style;
    }
}
