//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Gyroscope_Wrapper {
        
        private Vector3_Wrapper _rotationrate;
        
        private Vector3_Wrapper _rotationrateunbiased;
        
        private Vector3_Wrapper _gravity;
        
        private Vector3_Wrapper _useracceleration;
        
        private Quaternion_Wrapper _attitude;
        
        private bool _enabled;
        
        private float _updateinterval;
        
        public Vector3_Wrapper rotationRate {
            get {
                return this._rotationrate;
            }
            set {
                this._rotationrate = value;
            }
        }
        
        public Vector3_Wrapper rotationRateUnbiased {
            get {
                return this._rotationrateunbiased;
            }
            set {
                this._rotationrateunbiased = value;
            }
        }
        
        public Vector3_Wrapper gravity {
            get {
                return this._gravity;
            }
            set {
                this._gravity = value;
            }
        }
        
        public Vector3_Wrapper userAcceleration {
            get {
                return this._useracceleration;
            }
            set {
                this._useracceleration = value;
            }
        }
        
        public Quaternion_Wrapper attitude {
            get {
                return this._attitude;
            }
            set {
                this._attitude = value;
            }
        }
        
        public bool enabled {
            get {
                return _enabled;
            }
            set {
                _enabled = value;
            }
        }
        
        public float updateInterval {
            get {
                return _updateinterval;
            }
            set {
                _updateinterval = value;
            }
        }
    }
}
