//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class HLandingLeg_Wrapper {
        
        private string _constructid;
        
        private Part_Wrapper _localroot;
        
        private PartStates _state;
        
        private bool _hasstagingicon;
        
        private bool _isconnected;
        
        private bool _isattached;
        
        private bool _iscontrollable;
        
        private Rigidbody_Wrapper _rigidbody;
        
        private Orbit _orbit;
        
        private bool _landed;
        
        private bool _splashed;
        
        private string _classname;
        
        private int _classid;
        
        private BaseEventList_Wrapper _events;
        
        private BaseFieldList _fields;
        
        private BaseActionList _actions;
        
        private PartModuleList_Wrapper _modules;
        
        private EffectList_Wrapper _effects;
        
        private PartResourceList _resources;
        
        private bool _useguilayout;
        
        private bool _enabled;
        
        private Transform_Wrapper _transform;
        
        private Rigidbody2D_Wrapper _rigidbody2d;
        
        private Camera_Wrapper _camera;
        
        private Light_Wrapper _light;
        
        private Animation_Wrapper _animation;
        
        private ConstantForce_Wrapper _constantforce;
        
        private Renderer_Wrapper _renderer;
        
        private AudioSource_Wrapper _audio;
        
        private GUIText_Wrapper _guitext;
        
        private NetworkView_Wrapper _networkview;
        
        private GUIElement_Wrapper _guielement;
        
        private GUITexture_Wrapper _guitexture;
        
        private Collider_Wrapper _collider;
        
        private Collider2D_Wrapper _collider2d;
        
        private HingeJoint_Wrapper _hingejoint;
        
        private ParticleEmitter_Wrapper _particleemitter;
        
        private ParticleSystem_Wrapper _particlesystem;
        
        private GameObject_Wrapper _gameobject;
        
        private bool _active;
        
        private string _tag;
        
        private string _name;
        
        private UnityEngine.HideFlags _hideflags;
        
        public string ConstructID {
            get {
                return _constructid;
            }
            set {
                _constructid = value;
            }
        }
        
        public Part_Wrapper localRoot {
            get {
                return this._localroot;
            }
            set {
                this._localroot = value;
            }
        }
        
        public PartStates State {
            get {
                return _state;
            }
            set {
                _state = value;
            }
        }
        
        public bool hasStagingIcon {
            get {
                return _hasstagingicon;
            }
            set {
                _hasstagingicon = value;
            }
        }
        
        public bool isConnected {
            get {
                return _isconnected;
            }
            set {
                _isconnected = value;
            }
        }
        
        public bool isAttached {
            get {
                return _isattached;
            }
            set {
                _isattached = value;
            }
        }
        
        public bool isControllable {
            get {
                return _iscontrollable;
            }
            set {
                _iscontrollable = value;
            }
        }
        
        public Rigidbody_Wrapper Rigidbody {
            get {
                return this._rigidbody;
            }
            set {
                this._rigidbody = value;
            }
        }
        
        public Orbit orbit {
            get {
                return _orbit;
            }
            set {
                _orbit = value;
            }
        }
        
        public bool Landed {
            get {
                return _landed;
            }
            set {
                _landed = value;
            }
        }
        
        public bool Splashed {
            get {
                return _splashed;
            }
            set {
                _splashed = value;
            }
        }
        
        public string ClassName {
            get {
                return _classname;
            }
            set {
                _classname = value;
            }
        }
        
        public int ClassID {
            get {
                return _classid;
            }
            set {
                _classid = value;
            }
        }
        
        public BaseEventList_Wrapper Events {
            get {
                return this._events;
            }
            set {
                this._events = value;
            }
        }
        
        public BaseFieldList Fields {
            get {
                return _fields;
            }
            set {
                _fields = value;
            }
        }
        
        public BaseActionList Actions {
            get {
                return _actions;
            }
            set {
                _actions = value;
            }
        }
        
        public PartModuleList_Wrapper Modules {
            get {
                return this._modules;
            }
            set {
                this._modules = value;
            }
        }
        
        public EffectList_Wrapper Effects {
            get {
                return this._effects;
            }
            set {
                this._effects = value;
            }
        }
        
        public PartResourceList Resources {
            get {
                return _resources;
            }
            set {
                _resources = value;
            }
        }
        
        public bool useGUILayout {
            get {
                return _useguilayout;
            }
            set {
                _useguilayout = value;
            }
        }
        
        public bool enabled {
            get {
                return _enabled;
            }
            set {
                _enabled = value;
            }
        }
        
        public Transform_Wrapper transform {
            get {
                return this._transform;
            }
            set {
                this._transform = value;
            }
        }
        
        public Rigidbody_Wrapper rigidbody {
            get {
                return this._rigidbody;
            }
            set {
                this._rigidbody = value;
            }
        }
        
        public Rigidbody2D_Wrapper rigidbody2D {
            get {
                return this._rigidbody2d;
            }
            set {
                this._rigidbody2d = value;
            }
        }
        
        public Camera_Wrapper camera {
            get {
                return this._camera;
            }
            set {
                this._camera = value;
            }
        }
        
        public Light_Wrapper light {
            get {
                return this._light;
            }
            set {
                this._light = value;
            }
        }
        
        public Animation_Wrapper animation {
            get {
                return this._animation;
            }
            set {
                this._animation = value;
            }
        }
        
        public ConstantForce_Wrapper constantForce {
            get {
                return this._constantforce;
            }
            set {
                this._constantforce = value;
            }
        }
        
        public Renderer_Wrapper renderer {
            get {
                return this._renderer;
            }
            set {
                this._renderer = value;
            }
        }
        
        public AudioSource_Wrapper audio {
            get {
                return this._audio;
            }
            set {
                this._audio = value;
            }
        }
        
        public GUIText_Wrapper guiText {
            get {
                return this._guitext;
            }
            set {
                this._guitext = value;
            }
        }
        
        public NetworkView_Wrapper networkView {
            get {
                return this._networkview;
            }
            set {
                this._networkview = value;
            }
        }
        
        public GUIElement_Wrapper guiElement {
            get {
                return this._guielement;
            }
            set {
                this._guielement = value;
            }
        }
        
        public GUITexture_Wrapper guiTexture {
            get {
                return this._guitexture;
            }
            set {
                this._guitexture = value;
            }
        }
        
        public Collider_Wrapper collider {
            get {
                return this._collider;
            }
            set {
                this._collider = value;
            }
        }
        
        public Collider2D_Wrapper collider2D {
            get {
                return this._collider2d;
            }
            set {
                this._collider2d = value;
            }
        }
        
        public HingeJoint_Wrapper hingeJoint {
            get {
                return this._hingejoint;
            }
            set {
                this._hingejoint = value;
            }
        }
        
        public ParticleEmitter_Wrapper particleEmitter {
            get {
                return this._particleemitter;
            }
            set {
                this._particleemitter = value;
            }
        }
        
        public ParticleSystem_Wrapper particleSystem {
            get {
                return this._particlesystem;
            }
            set {
                this._particlesystem = value;
            }
        }
        
        public GameObject_Wrapper gameObject {
            get {
                return this._gameobject;
            }
            set {
                this._gameobject = value;
            }
        }
        
        public bool active {
            get {
                return _active;
            }
            set {
                _active = value;
            }
        }
        
        public string tag {
            get {
                return _tag;
            }
            set {
                _tag = value;
            }
        }
        
        public string name {
            get {
                return _name;
            }
            set {
                _name = value;
            }
        }
        
        public UnityEngine.HideFlags hideFlags {
            get {
                return _hideflags;
            }
            set {
                _hideflags = value;
            }
        }
    }
}
