//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class HostData_Wrapper {
        
        public bool useNat;
        
        public string gameType;
        
        public string gameName;
        
        public int connectedPlayers;
        
        public int playerLimit;
        
        public string[] ip;
        
        public int port;
        
        public bool passwordProtected;
        
        public string comment;
        
        public string guid;
    }
}
