//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class HostData_Wrapper {
        
        private bool _usenat;
        
        private string _gametype;
        
        private string _gamename;
        
        private int _connectedplayers;
        
        private int _playerlimit;
        
        private string[] _ip;
        
        private int _port;
        
        private bool _passwordprotected;
        
        private string _comment;
        
        private string _guid;
        
        public bool useNat {
            get {
                return _usenat;
            }
            set {
                _usenat = value;
            }
        }
        
        public string gameType {
            get {
                return _gametype;
            }
            set {
                _gametype = value;
            }
        }
        
        public string gameName {
            get {
                return _gamename;
            }
            set {
                _gamename = value;
            }
        }
        
        public int connectedPlayers {
            get {
                return _connectedplayers;
            }
            set {
                _connectedplayers = value;
            }
        }
        
        public int playerLimit {
            get {
                return _playerlimit;
            }
            set {
                _playerlimit = value;
            }
        }
        
        public string[] ip {
            get {
                return _ip;
            }
            set {
                _ip = value;
            }
        }
        
        public int port {
            get {
                return _port;
            }
            set {
                _port = value;
            }
        }
        
        public bool passwordProtected {
            get {
                return _passwordprotected;
            }
            set {
                _passwordprotected = value;
            }
        }
        
        public string comment {
            get {
                return _comment;
            }
            set {
                _comment = value;
            }
        }
        
        public string guid {
            get {
                return _guid;
            }
            set {
                _guid = value;
            }
        }
    }
}
