//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class HumanLimit_Wrapper {
        
        public bool useDefaultValues;
        
        public Vector3_Wrapper min;
        
        public Vector3_Wrapper max;
        
        public Vector3_Wrapper center;
        
        public float axisLength;
    }
}
