//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class InternalEmitParticleArguments_Wrapper {
        
        public Vector3_Wrapper pos;
        
        public Vector3_Wrapper velocity;
        
        public float size;
        
        public float energy;
        
        public Color_Wrapper color;
        
        public float rotation;
        
        public float angularVelocity;
    }
}
