//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class InternalNavBall_Wrapper {
        
        public string navBallName;
        
        public Transform_Wrapper navBall;
        
        public Vector3_Wrapper iconUp;
        
        public string progradeVectorName;
        
        public Transform_Wrapper progradeVector;
        
        public string retrogradeVectorName;
        
        public Transform_Wrapper retrogradeVector;
        
        public string progradeWaypointName;
        
        public Transform_Wrapper progradeWaypoint;
        
        public string retrogradeWaypointName;
        
        public Transform_Wrapper retrogradeWaypoint;
        
        public string retrogradeDeltaVName;
        
        public Transform_Wrapper retrogradeDeltaV;
        
        public string progradeDeltaVName;
        
        public Transform_Wrapper progradeDeltaV;
        
        public Vector3_Wrapper vesselOffset;
        
        public Vector3_Wrapper gaugeOffset;
        
        public Quaternion_Wrapper vesselOffsetRotation;
        
        public Quaternion_Wrapper gaugeOffsetRotation;
        
        public int moduleID;
        
        public InternalProp_Wrapper internalProp;
        
        public string ClassName;
        
        public int ClassID;
        
        public BaseEventList_Wrapper Events;
        
        public BaseFieldList Fields;
        
        public InternalModel_Wrapper internalModel;
        
        public Part_Wrapper part;
        
        public Vessel_Wrapper vessel;
        
        public bool useGUILayout;
        
        public bool enabled;
        
        public Transform_Wrapper transform;
        
        public Rigidbody_Wrapper rigidbody;
        
        public Rigidbody2D_Wrapper rigidbody2D;
        
        public Camera_Wrapper camera;
        
        public Light_Wrapper light;
        
        public Animation_Wrapper animation;
        
        public ConstantForce_Wrapper constantForce;
        
        public Renderer_Wrapper renderer;
        
        public AudioSource_Wrapper audio;
        
        public GUIText_Wrapper guiText;
        
        public NetworkView_Wrapper networkView;
        
        public GUIElement_Wrapper guiElement;
        
        public GUITexture_Wrapper guiTexture;
        
        public Collider_Wrapper collider;
        
        public Collider2D_Wrapper collider2D;
        
        public HingeJoint_Wrapper hingeJoint;
        
        public ParticleEmitter_Wrapper particleEmitter;
        
        public ParticleSystem_Wrapper particleSystem;
        
        public GameObject_Wrapper gameObject;
        
        public bool active;
        
        public string tag;
        
        public string name;
        
        public UnityEngine.HideFlags hideFlags;
    }
}
