//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class JointSuspension2D_Wrapper {
        
        private float _dampingratio;
        
        private float _frequency;
        
        private float _angle;
        
        public float dampingRatio {
            get {
                return _dampingratio;
            }
            set {
                _dampingratio = value;
            }
        }
        
        public float frequency {
            get {
                return _frequency;
            }
            set {
                _frequency = value;
            }
        }
        
        public float angle {
            get {
                return _angle;
            }
            set {
                _angle = value;
            }
        }
    }
}
