//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class JointLimits_Wrapper {
        
        private float _min;
        
        private float _minbounce;
        
        private float _max;
        
        private float _maxbounce;
        
        public float min {
            get {
                return _min;
            }
            set {
                _min = value;
            }
        }
        
        public float minBounce {
            get {
                return _minbounce;
            }
            set {
                _minbounce = value;
            }
        }
        
        public float max {
            get {
                return _max;
            }
            set {
                _max = value;
            }
        }
        
        public float maxBounce {
            get {
                return _maxbounce;
            }
            set {
                _maxbounce = value;
            }
        }
    }
}
