//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class KerbalExpressionAI_Wrapper {
        
        public ProtoCrewMember protoCrewMember;
        
        public Mesh_Wrapper idleMesh;
        
        public UnityEngine.Mesh[] wheeeMeshes;
        
        public UnityEngine.Mesh[] panicMeshes;
        
        public Transform_Wrapper headRef;
        
        public Transform_Wrapper neckJoint;
        
        public MeshFilter_Wrapper headMesh;
        
        public float panicLevel;
        
        public float wheeeLevel;
        
        public float idleThreshold;
        
        public float headBobAmount;
        
        public float updateInterval;
        
        public float noiseSeed;
        
        public float flight_velocity;
        
        public float flight_angularV;
        
        public float flight_gee;
        
        public float fearFactor;
        
        public bool useGUILayout;
        
        public bool enabled;
        
        public Transform_Wrapper transform;
        
        public Rigidbody_Wrapper rigidbody;
        
        public Rigidbody2D_Wrapper rigidbody2D;
        
        public Camera_Wrapper camera;
        
        public Light_Wrapper light;
        
        public Animation_Wrapper animation;
        
        public ConstantForce_Wrapper constantForce;
        
        public Renderer_Wrapper renderer;
        
        public AudioSource_Wrapper audio;
        
        public GUIText_Wrapper guiText;
        
        public NetworkView_Wrapper networkView;
        
        public GUIElement_Wrapper guiElement;
        
        public GUITexture_Wrapper guiTexture;
        
        public Collider_Wrapper collider;
        
        public Collider2D_Wrapper collider2D;
        
        public HingeJoint_Wrapper hingeJoint;
        
        public ParticleEmitter_Wrapper particleEmitter;
        
        public ParticleSystem_Wrapper particleSystem;
        
        public GameObject_Wrapper gameObject;
        
        public bool active;
        
        public string tag;
        
        public string name;
        
        public UnityEngine.HideFlags hideFlags;
    }
}
