//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Kerbal_Wrapper {
        
        public string crewMemberName;
        
        public float courage;
        
        public float stupidity;
        
        public bool isBadass;
        
        public ProtoCrewMember.RosterStatus rosterStatus;
        
        public Part_Wrapper InPart;
        
        public ProtoCrewMember protoCrewMember;
        
        public Camera_Wrapper kerbalCam;
        
        public float camBobAmount;
        
        public float noiseSeed;
        
        public bool randomizeOnStartup;
        
        public RenderTexture_Wrapper avatarTexture;
        
        public GameObject_Wrapper kerbalCamOverlay;
        
        public Transform_Wrapper camPivot;
        
        public Transform_Wrapper eyeTransform;
        
        public UnityEngine.Renderer[] textureTargets;
        
        public Texture2D_Wrapper textureStandard;
        
        public Texture2D_Wrapper textureVeteran;
        
        public Transform_Wrapper helmetTransform;
        
        public Transform_Wrapper headTransform;
        
        public Kerbal.States state;
        
        public float updateInterval;
        
        public float staticOverlayDuration;
        
        public bool showHelmet;
        
        public float avatarSize;
        
        public float textBoxSize;
        
        public Vector2_Wrapper screenPos;
        
        public Vessel_Wrapper InVessel;
        
        public bool useGUILayout;
        
        public bool enabled;
        
        public Transform_Wrapper transform;
        
        public Rigidbody_Wrapper rigidbody;
        
        public Rigidbody2D_Wrapper rigidbody2D;
        
        public Camera_Wrapper camera;
        
        public Light_Wrapper light;
        
        public Animation_Wrapper animation;
        
        public ConstantForce_Wrapper constantForce;
        
        public Renderer_Wrapper renderer;
        
        public AudioSource_Wrapper audio;
        
        public GUIText_Wrapper guiText;
        
        public NetworkView_Wrapper networkView;
        
        public GUIElement_Wrapper guiElement;
        
        public GUITexture_Wrapper guiTexture;
        
        public Collider_Wrapper collider;
        
        public Collider2D_Wrapper collider2D;
        
        public HingeJoint_Wrapper hingeJoint;
        
        public ParticleEmitter_Wrapper particleEmitter;
        
        public ParticleSystem_Wrapper particleSystem;
        
        public GameObject_Wrapper gameObject;
        
        public bool active;
        
        public string tag;
        
        public string name;
        
        public UnityEngine.HideFlags hideFlags;
    }
}
