//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class KerbalEVA_Wrapper {
        
        public float walkSpeed;
        
        public float strafeSpeed;
        
        public float runSpeed;
        
        public float turnRate;
        
        public float maxJumpForce;
        
        public float boundForce;
        
        public float boundSpeed;
        
        public float boundThreshold;
        
        public float swimSpeed;
        
        public float ladderClimbSpeed;
        
        public float ladderPushoffForce;
        
        public float minWalkingGee;
        
        public float minRunningGee;
        
        public float initialMass;
        
        public float massMultiplier;
        
        public Transform_Wrapper upperTorso;
        
        public Transform_Wrapper footPivot;
        
        public Transform_Wrapper referenceTransform;
        
        public KerbalAnimationManager Animations;
        
        public KerbalRagdollNode[] ragdollNodes;
        
        public UnityEngine.Collider[] characterColliders;
        
        public UnityEngine.Collider[] otherRagdollColliders;
        
        public KerbalFSM fsm;
        
        public bool JetpackDeployed;
        
        public bool lampOn;
        
        public GameObject_Wrapper headLamp;
        
        public bool splatEnabled;
        
        public float splatSpeed;
        
        public GameObject_Wrapper splatPrefab;
        
        public bool CharacterFrameMode;
        
        public bool CharacterFrameModeToggle;
        
        public int propellantResourceId;
        
        public float boundFrequency;
        
        public float boundSharpness;
        
        public float boundAttack;
        
        public float boundRelease;
        
        public float boundFallThreshold;
        
        public float flagReach;
        
        public float Kp;
        
        public float Ki;
        
        public float Kd;
        
        public float iC;
        
        public float rotPower;
        
        public float linPower;
        
        public float PropellantConsumption;
        
        public Vector3_Wrapper fFwd;
        
        public Vector3_Wrapper fUp;
        
        public Vector3_Wrapper fRgt;
        
        public bool isRagdoll;
        
        public bool canRecover;
        
        public float stumbleThreshold;
        
        public float hopThreshold;
        
        public float recoverThreshold;
        
        public double recoverTime;
        
        public float splatThreshold;
        
        public Transform_Wrapper ladderPivot;
        
        public string moduleName;
        
        public bool isEnabled;
        
        public ProtoPartModuleSnapshot_Wrapper snapshot;
        
        public bool Ready;
        
        public int flagItems;
        
        public double Fuel;
        
        public double FuelCapacity;
        
        public bool OnALadder;
        
        public string ClassName;
        
        public int ClassID;
        
        public BaseEventList_Wrapper Events;
        
        public BaseFieldList Fields;
        
        public string GUIName;
        
        public BaseActionList Actions;
        
        public Part_Wrapper part;
        
        public Vessel_Wrapper vessel;
        
        public bool useGUILayout;
        
        public bool enabled;
        
        public Transform_Wrapper transform;
        
        public Rigidbody_Wrapper rigidbody;
        
        public Rigidbody2D_Wrapper rigidbody2D;
        
        public Camera_Wrapper camera;
        
        public Light_Wrapper light;
        
        public Animation_Wrapper animation;
        
        public ConstantForce_Wrapper constantForce;
        
        public Renderer_Wrapper renderer;
        
        public AudioSource_Wrapper audio;
        
        public GUIText_Wrapper guiText;
        
        public NetworkView_Wrapper networkView;
        
        public GUIElement_Wrapper guiElement;
        
        public GUITexture_Wrapper guiTexture;
        
        public Collider_Wrapper collider;
        
        public Collider2D_Wrapper collider2D;
        
        public HingeJoint_Wrapper hingeJoint;
        
        public ParticleEmitter_Wrapper particleEmitter;
        
        public ParticleSystem_Wrapper particleSystem;
        
        public GameObject_Wrapper gameObject;
        
        public bool active;
        
        public string tag;
        
        public string name;
        
        public UnityEngine.HideFlags hideFlags;
    }
}
