//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class kerbalExpressionSystem_Wrapper {
        
        public ProtoCrewMember protoCrewMember;
        
        public Part_Wrapper evaPart;
        
        public Animator_Wrapper animator;
        
        public string expressionParameterName;
        
        public string varianceParameterName;
        
        public string secondaryVarianceParameterName;
        
        public string hasHelmetName;
        
        public string idleBoolName;
        
        public string idleFloatName;
        
        public Kerbal_Wrapper kerbal;
        
        public KerbalEVA_Wrapper kerbalEVA;
        
        public float panicLevel;
        
        public float wheeLevel;
        
        public float fearFactor;
        
        public float expression;
        
        public float expressionLerpRate;
        
        public float idleThreshold;
        
        public int idleRandomNumberLimitHelmet;
        
        public int idleRandomNumberLimitNoHelmet;
        
        public float varianceLerpRate;
        
        public float varianceUpdateInterval;
        
        public float varianceTimer;
        
        public float secondaryVarianceLerpRate;
        
        public float secondaryVarianceUpdateInterval;
        
        public float secondaryVarianceTimer;
        
        public float idleTimer;
        
        public float idleUpdateInterval;
        
        public int idlePlayChance;
        
        public float flight_velocity;
        
        public float flight_angularV;
        
        public float flight_gee;
        
        public bool isIVAController;
        
        public bool useGUILayout;
        
        public bool enabled;
        
        public Transform_Wrapper transform;
        
        public Rigidbody_Wrapper rigidbody;
        
        public Rigidbody2D_Wrapper rigidbody2D;
        
        public Camera_Wrapper camera;
        
        public Light_Wrapper light;
        
        public Animation_Wrapper animation;
        
        public ConstantForce_Wrapper constantForce;
        
        public Renderer_Wrapper renderer;
        
        public AudioSource_Wrapper audio;
        
        public GUIText_Wrapper guiText;
        
        public NetworkView_Wrapper networkView;
        
        public GUIElement_Wrapper guiElement;
        
        public GUITexture_Wrapper guiTexture;
        
        public Collider_Wrapper collider;
        
        public Collider2D_Wrapper collider2D;
        
        public HingeJoint_Wrapper hingeJoint;
        
        public ParticleEmitter_Wrapper particleEmitter;
        
        public ParticleSystem_Wrapper particleSystem;
        
        public GameObject_Wrapper gameObject;
        
        public bool active;
        
        public string tag;
        
        public string name;
        
        public UnityEngine.HideFlags hideFlags;
    }
}
