//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class KSPUtil_Wrapper {
        
        public int Minute;
        
        public int Hour;
        
        public int Day;
        
        public int Year;
        
        public int KerbinDay;
        
        public int KerbinYear;
        
        public int EarthDay;
        
        public int EarthYear;
        
        public string ApplicationRootPath;
    }
}
