//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class LineRenderer_Wrapper {
        
        private bool _useworldspace;
        
        private bool _ispartofstaticbatch;
        
        private Matrix4x4_Wrapper _worldtolocalmatrix;
        
        private Matrix4x4_Wrapper _localtoworldmatrix;
        
        private bool _enabled;
        
        private bool _castshadows;
        
        private bool _receiveshadows;
        
        private Material_Wrapper _material;
        
        private Material_Wrapper _sharedmaterial;
        
        private UnityEngine.Material[] _sharedmaterials;
        
        private UnityEngine.Material[] _materials;
        
        private Bounds_Wrapper _bounds;
        
        private int _lightmapindex;
        
        private Vector4_Wrapper _lightmaptilingoffset;
        
        private bool _isvisible;
        
        private bool _uselightprobes;
        
        private Transform_Wrapper _lightprobeanchor;
        
        private string _sortinglayername;
        
        private int _sortinglayerid;
        
        private int _sortingorder;
        
        private Transform_Wrapper _transform;
        
        private Rigidbody_Wrapper _rigidbody;
        
        private Rigidbody2D_Wrapper _rigidbody2d;
        
        private Camera_Wrapper _camera;
        
        private Light_Wrapper _light;
        
        private Animation_Wrapper _animation;
        
        private ConstantForce_Wrapper _constantforce;
        
        private Renderer_Wrapper _renderer;
        
        private AudioSource_Wrapper _audio;
        
        private GUIText_Wrapper _guitext;
        
        private NetworkView_Wrapper _networkview;
        
        private GUIElement_Wrapper _guielement;
        
        private GUITexture_Wrapper _guitexture;
        
        private Collider_Wrapper _collider;
        
        private Collider2D_Wrapper _collider2d;
        
        private HingeJoint_Wrapper _hingejoint;
        
        private ParticleEmitter_Wrapper _particleemitter;
        
        private ParticleSystem_Wrapper _particlesystem;
        
        private GameObject_Wrapper _gameobject;
        
        private bool _active;
        
        private string _tag;
        
        private string _name;
        
        private UnityEngine.HideFlags _hideflags;
        
        public bool useWorldSpace {
            get {
                return _useworldspace;
            }
            set {
                _useworldspace = value;
            }
        }
        
        public bool isPartOfStaticBatch {
            get {
                return _ispartofstaticbatch;
            }
            set {
                _ispartofstaticbatch = value;
            }
        }
        
        public Matrix4x4_Wrapper worldToLocalMatrix {
            get {
                return this._worldtolocalmatrix;
            }
            set {
                this._worldtolocalmatrix = value;
            }
        }
        
        public Matrix4x4_Wrapper localToWorldMatrix {
            get {
                return this._localtoworldmatrix;
            }
            set {
                this._localtoworldmatrix = value;
            }
        }
        
        public bool enabled {
            get {
                return _enabled;
            }
            set {
                _enabled = value;
            }
        }
        
        public bool castShadows {
            get {
                return _castshadows;
            }
            set {
                _castshadows = value;
            }
        }
        
        public bool receiveShadows {
            get {
                return _receiveshadows;
            }
            set {
                _receiveshadows = value;
            }
        }
        
        public Material_Wrapper material {
            get {
                return this._material;
            }
            set {
                this._material = value;
            }
        }
        
        public Material_Wrapper sharedMaterial {
            get {
                return this._sharedmaterial;
            }
            set {
                this._sharedmaterial = value;
            }
        }
        
        public UnityEngine.Material[] sharedMaterials {
            get {
                return _sharedmaterials;
            }
            set {
                _sharedmaterials = value;
            }
        }
        
        public UnityEngine.Material[] materials {
            get {
                return _materials;
            }
            set {
                _materials = value;
            }
        }
        
        public Bounds_Wrapper bounds {
            get {
                return this._bounds;
            }
            set {
                this._bounds = value;
            }
        }
        
        public int lightmapIndex {
            get {
                return _lightmapindex;
            }
            set {
                _lightmapindex = value;
            }
        }
        
        public Vector4_Wrapper lightmapTilingOffset {
            get {
                return this._lightmaptilingoffset;
            }
            set {
                this._lightmaptilingoffset = value;
            }
        }
        
        public bool isVisible {
            get {
                return _isvisible;
            }
            set {
                _isvisible = value;
            }
        }
        
        public bool useLightProbes {
            get {
                return _uselightprobes;
            }
            set {
                _uselightprobes = value;
            }
        }
        
        public Transform_Wrapper lightProbeAnchor {
            get {
                return this._lightprobeanchor;
            }
            set {
                this._lightprobeanchor = value;
            }
        }
        
        public string sortingLayerName {
            get {
                return _sortinglayername;
            }
            set {
                _sortinglayername = value;
            }
        }
        
        public int sortingLayerID {
            get {
                return _sortinglayerid;
            }
            set {
                _sortinglayerid = value;
            }
        }
        
        public int sortingOrder {
            get {
                return _sortingorder;
            }
            set {
                _sortingorder = value;
            }
        }
        
        public Transform_Wrapper transform {
            get {
                return this._transform;
            }
            set {
                this._transform = value;
            }
        }
        
        public Rigidbody_Wrapper rigidbody {
            get {
                return this._rigidbody;
            }
            set {
                this._rigidbody = value;
            }
        }
        
        public Rigidbody2D_Wrapper rigidbody2D {
            get {
                return this._rigidbody2d;
            }
            set {
                this._rigidbody2d = value;
            }
        }
        
        public Camera_Wrapper camera {
            get {
                return this._camera;
            }
            set {
                this._camera = value;
            }
        }
        
        public Light_Wrapper light {
            get {
                return this._light;
            }
            set {
                this._light = value;
            }
        }
        
        public Animation_Wrapper animation {
            get {
                return this._animation;
            }
            set {
                this._animation = value;
            }
        }
        
        public ConstantForce_Wrapper constantForce {
            get {
                return this._constantforce;
            }
            set {
                this._constantforce = value;
            }
        }
        
        public Renderer_Wrapper renderer {
            get {
                return this._renderer;
            }
            set {
                this._renderer = value;
            }
        }
        
        public AudioSource_Wrapper audio {
            get {
                return this._audio;
            }
            set {
                this._audio = value;
            }
        }
        
        public GUIText_Wrapper guiText {
            get {
                return this._guitext;
            }
            set {
                this._guitext = value;
            }
        }
        
        public NetworkView_Wrapper networkView {
            get {
                return this._networkview;
            }
            set {
                this._networkview = value;
            }
        }
        
        public GUIElement_Wrapper guiElement {
            get {
                return this._guielement;
            }
            set {
                this._guielement = value;
            }
        }
        
        public GUITexture_Wrapper guiTexture {
            get {
                return this._guitexture;
            }
            set {
                this._guitexture = value;
            }
        }
        
        public Collider_Wrapper collider {
            get {
                return this._collider;
            }
            set {
                this._collider = value;
            }
        }
        
        public Collider2D_Wrapper collider2D {
            get {
                return this._collider2d;
            }
            set {
                this._collider2d = value;
            }
        }
        
        public HingeJoint_Wrapper hingeJoint {
            get {
                return this._hingejoint;
            }
            set {
                this._hingejoint = value;
            }
        }
        
        public ParticleEmitter_Wrapper particleEmitter {
            get {
                return this._particleemitter;
            }
            set {
                this._particleemitter = value;
            }
        }
        
        public ParticleSystem_Wrapper particleSystem {
            get {
                return this._particlesystem;
            }
            set {
                this._particlesystem = value;
            }
        }
        
        public GameObject_Wrapper gameObject {
            get {
                return this._gameobject;
            }
            set {
                this._gameobject = value;
            }
        }
        
        public bool active {
            get {
                return _active;
            }
            set {
                _active = value;
            }
        }
        
        public string tag {
            get {
                return _tag;
            }
            set {
                _tag = value;
            }
        }
        
        public string name {
            get {
                return _name;
            }
            set {
                _name = value;
            }
        }
        
        public UnityEngine.HideFlags hideFlags {
            get {
                return _hideflags;
            }
            set {
                _hideflags = value;
            }
        }
    }
}
