//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class LocalUser_Wrapper {
        
        private UnityEngine.SocialPlatforms.IUserProfile[] _friends;
        
        private bool _authenticated;
        
        private bool _underage;
        
        private string _username;
        
        private string _id;
        
        private bool _isfriend;
        
        private UnityEngine.SocialPlatforms.UserState _state;
        
        private Texture2D_Wrapper _image;
        
        public UnityEngine.SocialPlatforms.IUserProfile[] friends {
            get {
                return _friends;
            }
            set {
                _friends = value;
            }
        }
        
        public bool authenticated {
            get {
                return _authenticated;
            }
            set {
                _authenticated = value;
            }
        }
        
        public bool underage {
            get {
                return _underage;
            }
            set {
                _underage = value;
            }
        }
        
        public string userName {
            get {
                return _username;
            }
            set {
                _username = value;
            }
        }
        
        public string id {
            get {
                return _id;
            }
            set {
                _id = value;
            }
        }
        
        public bool isFriend {
            get {
                return _isfriend;
            }
            set {
                _isfriend = value;
            }
        }
        
        public UnityEngine.SocialPlatforms.UserState state {
            get {
                return _state;
            }
            set {
                _state = value;
            }
        }
        
        public Texture2D_Wrapper image {
            get {
                return this._image;
            }
            set {
                this._image = value;
            }
        }
    }
}
