//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class MainMenu_Wrapper {
        
        public TextButton3D_Wrapper startBtn;
        
        public TextButton3D_Wrapper instrcBtn;
        
        public TextButton3D_Wrapper commBtn;
        
        public TextButton3D_Wrapper spaceportBtn;
        
        public TextButton3D_Wrapper quitBtn;
        
        public TextButton3D_Wrapper updBtn;
        
        public TextButton3D_Wrapper settingBtn;
        
        public TextButton3D_Wrapper creditsBtn;
        
        public TextButton3D_Wrapper unitTestsBtn;
        
        public TextButton3D_Wrapper newGameBtn;
        
        public TextButton3D_Wrapper continueBtn;
        
        public TextButton3D_Wrapper trainingBtn;
        
        public TextButton3D_Wrapper scenariosBtn;
        
        public TextButton3D_Wrapper backBtn;
        
        public UnityEngine.GUISkin guiSkin;
        
        public Texture_Wrapper careerIcon;
        
        public Texture_Wrapper scienceSandboxIcon;
        
        public Texture_Wrapper sandboxIcon;
        
        public Texture_Wrapper scenarioIcon;
        
        public Texture_Wrapper tutorialIcon;
        
        public MainMenuEnvLogic_Wrapper envLogic;
        
        public string KSPsiteURL;
        
        public string SpaceportURL;
        
        public string DefaultFlagURL;
        
        public bool useGUILayout;
        
        public bool enabled;
        
        public Transform_Wrapper transform;
        
        public Rigidbody_Wrapper rigidbody;
        
        public Rigidbody2D_Wrapper rigidbody2D;
        
        public Camera_Wrapper camera;
        
        public Light_Wrapper light;
        
        public Animation_Wrapper animation;
        
        public ConstantForce_Wrapper constantForce;
        
        public Renderer_Wrapper renderer;
        
        public AudioSource_Wrapper audio;
        
        public GUIText_Wrapper guiText;
        
        public NetworkView_Wrapper networkView;
        
        public GUIElement_Wrapper guiElement;
        
        public GUITexture_Wrapper guiTexture;
        
        public Collider_Wrapper collider;
        
        public Collider2D_Wrapper collider2D;
        
        public HingeJoint_Wrapper hingeJoint;
        
        public ParticleEmitter_Wrapper particleEmitter;
        
        public ParticleSystem_Wrapper particleSystem;
        
        public GameObject_Wrapper gameObject;
        
        public bool active;
        
        public string tag;
        
        public string name;
        
        public UnityEngine.HideFlags hideFlags;
    }
}
