//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class ManeuverGizmo_Wrapper {
        
        public ManeuverGizmoHandle_Wrapper handlePrograde;
        
        public ManeuverGizmoHandle_Wrapper handleRetrograde;
        
        public ManeuverGizmoHandle_Wrapper handleNormal;
        
        public ManeuverGizmoHandle_Wrapper handleAntiNormal;
        
        public ManeuverGizmoHandle_Wrapper handleRadialIn;
        
        public ManeuverGizmoHandle_Wrapper handleRadialOut;
        
        public Camera_Wrapper camera;
        
        public UnityEngine.Transform[] cameraFacingBillboards;
        
        public Transform_Wrapper grabArea;
        
        public Transform_Wrapper buttonRoot;
        
        public Transform_Wrapper handlesRoot;
        
        public ScreenSafeUIButton_Wrapper deleteBtn;
        
        public ScreenSafeUIButton_Wrapper plusOrbitBtn;
        
        public ScreenSafeUIButton_Wrapper minusOrbitbtn;
        
        public double sensitivity;
        
        public double multiplier;
        
        public float screenSize;
        
        public Vector3d_Wrapper DeltaV;
        
        public double UT;
        
        public int orbitsAdded;
        
        public ManeuverGizmo.HandlesUpdatedCallback OnGizmoUpdated;
        
        public Callback OnGizmoDraggedOff;
        
        public Callback OnMinimize;
        
        public Callback OnDelete;
        
        public Orbit patchBefore;
        
        public Orbit patchAhead;
        
        public PatchedConicRenderer_Wrapper renderer;
        
        public bool HasMouseFocus;
        
        public bool MouseOverGizmo;
        
        public bool useGUILayout;
        
        public bool enabled;
        
        public Transform_Wrapper transform;
        
        public Rigidbody_Wrapper rigidbody;
        
        public Rigidbody2D_Wrapper rigidbody2D;
        
        public Light_Wrapper light;
        
        public Animation_Wrapper animation;
        
        public ConstantForce_Wrapper constantForce;
        
        public AudioSource_Wrapper audio;
        
        public GUIText_Wrapper guiText;
        
        public NetworkView_Wrapper networkView;
        
        public GUIElement_Wrapper guiElement;
        
        public GUITexture_Wrapper guiTexture;
        
        public Collider_Wrapper collider;
        
        public Collider2D_Wrapper collider2D;
        
        public HingeJoint_Wrapper hingeJoint;
        
        public ParticleEmitter_Wrapper particleEmitter;
        
        public ParticleSystem_Wrapper particleSystem;
        
        public GameObject_Wrapper gameObject;
        
        public bool active;
        
        public string tag;
        
        public string name;
        
        public UnityEngine.HideFlags hideFlags;
    }
}
