//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class MatchTargetWeightMask_Wrapper {
        
        private Vector3_Wrapper _positionxyzweight;
        
        private float _rotationweight;
        
        public Vector3_Wrapper positionXYZWeight {
            get {
                return this._positionxyzweight;
            }
            set {
                this._positionxyzweight = value;
            }
        }
        
        public float rotationWeight {
            get {
                return _rotationweight;
            }
            set {
                _rotationweight = value;
            }
        }
    }
}
