//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class MCAvatarController_Wrapper {
        
        public KerbalInstructor_Wrapper avatar;
        
        public float rangeWeight;
        
        public CharacterAnimationState anim_mc_happyA_idle;
        
        public CharacterAnimationState anim_mc_happyB_idle;
        
        public CharacterAnimationState anim_mc_happyC_idle;
        
        public CharacterAnimationState anim_mc_idle;
        
        public CharacterAnimationState anim_mc_idle_drinkCoffee;
        
        public CharacterAnimationState anim_mc_lookLeft;
        
        public CharacterAnimationState anim_mc_lookRight;
        
        public CharacterAnimationState anim_mc_lookUp;
        
        public CharacterAnimationState anim_mc_scaredA_idle;
        
        public CharacterAnimationState anim_mc_scaredB_idle;
        
        public CharacterAnimationState anim_mc_scaredC_idle;
        
        public CharacterAnimationState anim_sound_acceptA;
        
        public CharacterAnimationState anim_sound_acceptB;
        
        public CharacterAnimationState anim_sound_acceptC;
        
        public CharacterAnimationState anim_sound_declineA;
        
        public CharacterAnimationState anim_sound_declineB;
        
        public CharacterAnimationState anim_sound_cancelA;
        
        public CharacterAnimationState anim_sound_cancelB;
        
        public CharacterAnimationState anim_sound_selectNormal;
        
        public CharacterAnimationState anim_sound_selectEasy;
        
        public CharacterAnimationState anim_sound_selectHard;
        
        public CharacterAnimationState anim_sound_selectA;
        
        public CharacterAnimationState anim_sound_selectB;
        
        public CharacterAnimationState anim_sound_selectC;
        
        public CharacterAnimationState anim_sound_selectD;
        
        public CharacterAnimationState anim_sound_selectE;
        
        public System.Collections.Generic.List<MCAvatarController.AvatarState> states;
        
        public bool DrawDebugPanel;
        
        public string Comment;
        
        public bool useGUILayout;
        
        public bool enabled;
        
        public Transform_Wrapper transform;
        
        public Rigidbody_Wrapper rigidbody;
        
        public Rigidbody2D_Wrapper rigidbody2D;
        
        public Camera_Wrapper camera;
        
        public Light_Wrapper light;
        
        public Animation_Wrapper animation;
        
        public ConstantForce_Wrapper constantForce;
        
        public Renderer_Wrapper renderer;
        
        public AudioSource_Wrapper audio;
        
        public GUIText_Wrapper guiText;
        
        public NetworkView_Wrapper networkView;
        
        public GUIElement_Wrapper guiElement;
        
        public GUITexture_Wrapper guiTexture;
        
        public Collider_Wrapper collider;
        
        public Collider2D_Wrapper collider2D;
        
        public HingeJoint_Wrapper hingeJoint;
        
        public ParticleEmitter_Wrapper particleEmitter;
        
        public ParticleSystem_Wrapper particleSystem;
        
        public GameObject_Wrapper gameObject;
        
        public bool active;
        
        public string tag;
        
        public string name;
        
        public UnityEngine.HideFlags hideFlags;
    }
}
