//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class MemoryStream_Wrapper {
        
        private long _length;
        
        private int _capacity;
        
        private bool _canread;
        
        private bool _canseek;
        
        private bool _canwrite;
        
        private long _position;
        
        public long Length {
            get {
                return _length;
            }
            set {
                _length = value;
            }
        }
        
        public int Capacity {
            get {
                return _capacity;
            }
            set {
                _capacity = value;
            }
        }
        
        public bool CanRead {
            get {
                return _canread;
            }
            set {
                _canread = value;
            }
        }
        
        public bool CanSeek {
            get {
                return _canseek;
            }
            set {
                _canseek = value;
            }
        }
        
        public bool CanWrite {
            get {
                return _canwrite;
            }
            set {
                _canwrite = value;
            }
        }
        
        public long Position {
            get {
                return _position;
            }
            set {
                _position = value;
            }
        }
    }
}
