//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Mesh_Wrapper {
        
        private bool _isreadable;
        
        private UnityEngine.Vector3[] _vertices;
        
        private UnityEngine.Vector3[] _normals;
        
        private UnityEngine.Vector4[] _tangents;
        
        private UnityEngine.Vector2[] _uv;
        
        private UnityEngine.Vector2[] _uv2;
        
        private UnityEngine.Vector2[] _uv1;
        
        private Bounds_Wrapper _bounds;
        
        private UnityEngine.Color[] _colors;
        
        private UnityEngine.Color32[] _colors32;
        
        private int[] _triangles;
        
        private int _vertexcount;
        
        private int _submeshcount;
        
        private UnityEngine.BoneWeight[] _boneweights;
        
        private UnityEngine.Matrix4x4[] _bindposes;
        
        private int _blendshapecount;
        
        private string _name;
        
        private UnityEngine.HideFlags _hideflags;
        
        public bool isReadable {
            get {
                return _isreadable;
            }
            set {
                _isreadable = value;
            }
        }
        
        public UnityEngine.Vector3[] vertices {
            get {
                return _vertices;
            }
            set {
                _vertices = value;
            }
        }
        
        public UnityEngine.Vector3[] normals {
            get {
                return _normals;
            }
            set {
                _normals = value;
            }
        }
        
        public UnityEngine.Vector4[] tangents {
            get {
                return _tangents;
            }
            set {
                _tangents = value;
            }
        }
        
        public UnityEngine.Vector2[] uv {
            get {
                return _uv;
            }
            set {
                _uv = value;
            }
        }
        
        public UnityEngine.Vector2[] uv2 {
            get {
                return _uv2;
            }
            set {
                _uv2 = value;
            }
        }
        
        public UnityEngine.Vector2[] uv1 {
            get {
                return _uv1;
            }
            set {
                _uv1 = value;
            }
        }
        
        public Bounds_Wrapper bounds {
            get {
                return this._bounds;
            }
            set {
                this._bounds = value;
            }
        }
        
        public UnityEngine.Color[] colors {
            get {
                return _colors;
            }
            set {
                _colors = value;
            }
        }
        
        public UnityEngine.Color32[] colors32 {
            get {
                return _colors32;
            }
            set {
                _colors32 = value;
            }
        }
        
        public int[] triangles {
            get {
                return _triangles;
            }
            set {
                _triangles = value;
            }
        }
        
        public int vertexCount {
            get {
                return _vertexcount;
            }
            set {
                _vertexcount = value;
            }
        }
        
        public int subMeshCount {
            get {
                return _submeshcount;
            }
            set {
                _submeshcount = value;
            }
        }
        
        public UnityEngine.BoneWeight[] boneWeights {
            get {
                return _boneweights;
            }
            set {
                _boneweights = value;
            }
        }
        
        public UnityEngine.Matrix4x4[] bindposes {
            get {
                return _bindposes;
            }
            set {
                _bindposes = value;
            }
        }
        
        public int blendShapeCount {
            get {
                return _blendshapecount;
            }
            set {
                _blendshapecount = value;
            }
        }
        
        public string name {
            get {
                return _name;
            }
            set {
                _name = value;
            }
        }
        
        public UnityEngine.HideFlags hideFlags {
            get {
                return _hideflags;
            }
            set {
                _hideflags = value;
            }
        }
    }
}
