//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class MovieTexture_Wrapper {
        
        public AudioClip_Wrapper audioClip;
        
        public bool loop;
        
        public bool isPlaying;
        
        public bool isReadyToPlay;
        
        public float duration;
        
        public int width;
        
        public int height;
        
        public UnityEngine.FilterMode filterMode;
        
        public int anisoLevel;
        
        public UnityEngine.TextureWrapMode wrapMode;
        
        public float mipMapBias;
        
        public Vector2_Wrapper texelSize;
        
        public string name;
        
        public UnityEngine.HideFlags hideFlags;
    }
}
