//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class MultiOptionDialog_Wrapper {
        
        public DialogOption[] Options;
        
        public UnityEngine.GUISkin guiSkin;
        
        public string title;
        
        public string message;
        
        public Rect_Wrapper dialogRect;
        
        public Callback DrawCustomContent;
        
        public int id;
    }
}
