//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class NavMeshPath_Wrapper {
        
        private UnityEngine.Vector3[] _corners;
        
        private UnityEngine.NavMeshPathStatus _status;
        
        public UnityEngine.Vector3[] corners {
            get {
                return _corners;
            }
            set {
                _corners = value;
            }
        }
        
        public UnityEngine.NavMeshPathStatus status {
            get {
                return _status;
            }
            set {
                _status = value;
            }
        }
    }
}
