//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class NetworkViewID_Wrapper {
        
        private bool _ismine;
        
        private NetworkPlayer_Wrapper _owner;
        
        public bool isMine {
            get {
                return _ismine;
            }
            set {
                _ismine = value;
            }
        }
        
        public NetworkPlayer_Wrapper owner {
            get {
                return this._owner;
            }
            set {
                this._owner = value;
            }
        }
    }
}
