//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    [SocketCommon.Attributes.InstanceNameAttribute("unassigned")]
    public class NetworkViewID_Wrapper {
        
        public NetworkViewID_Wrapper unassigned;
        
        public bool isMine;
        
        public NetworkPlayer_Wrapper owner;
    }
}
