//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class OffMeshLinkData_Wrapper {
        
        private bool _valid;
        
        private bool _activated;
        
        private UnityEngine.OffMeshLinkType _linktype;
        
        private Vector3_Wrapper _startpos;
        
        private Vector3_Wrapper _endpos;
        
        private OffMeshLink_Wrapper _offmeshlink;
        
        public bool valid {
            get {
                return _valid;
            }
            set {
                _valid = value;
            }
        }
        
        public bool activated {
            get {
                return _activated;
            }
            set {
                _activated = value;
            }
        }
        
        public UnityEngine.OffMeshLinkType linkType {
            get {
                return _linktype;
            }
            set {
                _linktype = value;
            }
        }
        
        public Vector3_Wrapper startPos {
            get {
                return this._startpos;
            }
            set {
                this._startpos = value;
            }
        }
        
        public Vector3_Wrapper endPos {
            get {
                return this._endpos;
            }
            set {
                this._endpos = value;
            }
        }
        
        public OffMeshLink_Wrapper offMeshLink {
            get {
                return this._offmeshlink;
            }
            set {
                this._offmeshlink = value;
            }
        }
    }
}
