//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class OrbitSnapshot_Wrapper {
        
        public double semiMajorAxis;
        
        public double eccentricity;
        
        public double inclination;
        
        public double argOfPeriapsis;
        
        public double LAN;
        
        public double meanAnomalyAtEpoch;
        
        public double epoch;
        
        public int ReferenceBodyIndex;
    }
}
