//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class PhysicMaterial_Wrapper {
        
        private float _dynamicfriction;
        
        private float _staticfriction;
        
        private float _bounciness;
        
        private float _bouncyness;
        
        private Vector3_Wrapper _frictiondirection2;
        
        private float _dynamicfriction2;
        
        private float _staticfriction2;
        
        private UnityEngine.PhysicMaterialCombine _frictioncombine;
        
        private UnityEngine.PhysicMaterialCombine _bouncecombine;
        
        private Vector3_Wrapper _frictiondirection;
        
        private string _name;
        
        private UnityEngine.HideFlags _hideflags;
        
        public float dynamicFriction {
            get {
                return _dynamicfriction;
            }
            set {
                _dynamicfriction = value;
            }
        }
        
        public float staticFriction {
            get {
                return _staticfriction;
            }
            set {
                _staticfriction = value;
            }
        }
        
        public float bounciness {
            get {
                return _bounciness;
            }
            set {
                _bounciness = value;
            }
        }
        
        public float bouncyness {
            get {
                return _bouncyness;
            }
            set {
                _bouncyness = value;
            }
        }
        
        public Vector3_Wrapper frictionDirection2 {
            get {
                return this._frictiondirection2;
            }
            set {
                this._frictiondirection2 = value;
            }
        }
        
        public float dynamicFriction2 {
            get {
                return _dynamicfriction2;
            }
            set {
                _dynamicfriction2 = value;
            }
        }
        
        public float staticFriction2 {
            get {
                return _staticfriction2;
            }
            set {
                _staticfriction2 = value;
            }
        }
        
        public UnityEngine.PhysicMaterialCombine frictionCombine {
            get {
                return _frictioncombine;
            }
            set {
                _frictioncombine = value;
            }
        }
        
        public UnityEngine.PhysicMaterialCombine bounceCombine {
            get {
                return _bouncecombine;
            }
            set {
                _bouncecombine = value;
            }
        }
        
        public Vector3_Wrapper frictionDirection {
            get {
                return this._frictiondirection;
            }
            set {
                this._frictiondirection = value;
            }
        }
        
        public string name {
            get {
                return _name;
            }
            set {
                _name = value;
            }
        }
        
        public UnityEngine.HideFlags hideFlags {
            get {
                return _hideflags;
            }
            set {
                _hideflags = value;
            }
        }
    }
}
