//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class PhysicsMaterial2D_Wrapper {
        
        public float bounciness;
        
        public float friction;
        
        public string name;
        
        public UnityEngine.HideFlags hideFlags;
    }
}
