//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Physics_Wrapper {
        
        public int kIgnoreRaycastLayer;
        
        public int kDefaultRaycastLayers;
        
        public int kAllLayers;
        
        public int IgnoreRaycastLayer;
        
        public int DefaultRaycastLayers;
        
        public int AllLayers;
        
        public Vector3_Wrapper gravity;
        
        public float minPenetrationForPenalty;
        
        public float bounceThreshold;
        
        public float bounceTreshold;
        
        public float sleepVelocity;
        
        public float sleepAngularVelocity;
        
        public float maxAngularVelocity;
        
        public int solverIterationCount;
        
        public float penetrationPenaltyForce;
    }
}
