//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class PhysicMaterial_Wrapper {
        
        public float dynamicFriction;
        
        public float staticFriction;
        
        public float bounciness;
        
        public float bouncyness;
        
        public Vector3_Wrapper frictionDirection2;
        
        public float dynamicFriction2;
        
        public float staticFriction2;
        
        public UnityEngine.PhysicMaterialCombine frictionCombine;
        
        public UnityEngine.PhysicMaterialCombine bounceCombine;
        
        public Vector3_Wrapper frictionDirection;
        
        public string name;
        
        public UnityEngine.HideFlags hideFlags;
    }
}
