//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Physics_Wrapper {
        
        public int _kIgnoreRaycastLayer_wrapped;
        
        public int _kDefaultRaycastLayers_wrapped;
        
        public int _kAllLayers_wrapped;
        
        public int _IgnoreRaycastLayer_wrapped;
        
        public int _DefaultRaycastLayers_wrapped;
        
        public int _AllLayers_wrapped;
    }
}
