//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Ping_Wrapper {
        
        private bool _isdone;
        
        private int _time;
        
        private string _ip;
        
        public bool isDone {
            get {
                return _isdone;
            }
            set {
                _isdone = value;
            }
        }
        
        public int time {
            get {
                return _time;
            }
            set {
                _time = value;
            }
        }
        
        public string ip {
            get {
                return _ip;
            }
            set {
                _ip = value;
            }
        }
    }
}
