//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Plane_Wrapper {
        
        private Vector3_Wrapper _normal;
        
        private float _distance;
        
        public Vector3_Wrapper normal {
            get {
                return this._normal;
            }
            set {
                this._normal = value;
            }
        }
        
        public float distance {
            get {
                return _distance;
            }
            set {
                _distance = value;
            }
        }
    }
}
