//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class PlayerPrefsException_Wrapper {
        
        public string Message;
        
        public System.Collections.IDictionary Data;
        
        public System.Exception InnerException;
        
        public System.Reflection.MethodBase TargetSite;
        
        public string StackTrace;
        
        public string HelpLink;
        
        public string Source;
        
        public int HResult;
    }
}
