//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class ProceduralMaterial_Wrapper {
        
        private UnityEngine.ProceduralCacheSize _cachesize;
        
        private int _animationupdaterate;
        
        private bool _isprocessing;
        
        private bool _iscacheddataavailable;
        
        private bool _isloadtimegenerated;
        
        private UnityEngine.ProceduralLoadingBehavior _loadingbehavior;
        
        private string _preset;
        
        private bool _isreadable;
        
        private Shader_Wrapper _shader;
        
        private Color_Wrapper _color;
        
        private Texture_Wrapper _maintexture;
        
        private Vector2_Wrapper _maintextureoffset;
        
        private Vector2_Wrapper _maintexturescale;
        
        private int _passcount;
        
        private int _renderqueue;
        
        private string[] _shaderkeywords;
        
        private string _name;
        
        private UnityEngine.HideFlags _hideflags;
        
        public UnityEngine.ProceduralCacheSize cacheSize {
            get {
                return _cachesize;
            }
            set {
                _cachesize = value;
            }
        }
        
        public int animationUpdateRate {
            get {
                return _animationupdaterate;
            }
            set {
                _animationupdaterate = value;
            }
        }
        
        public bool isProcessing {
            get {
                return _isprocessing;
            }
            set {
                _isprocessing = value;
            }
        }
        
        public bool isCachedDataAvailable {
            get {
                return _iscacheddataavailable;
            }
            set {
                _iscacheddataavailable = value;
            }
        }
        
        public bool isLoadTimeGenerated {
            get {
                return _isloadtimegenerated;
            }
            set {
                _isloadtimegenerated = value;
            }
        }
        
        public UnityEngine.ProceduralLoadingBehavior loadingBehavior {
            get {
                return _loadingbehavior;
            }
            set {
                _loadingbehavior = value;
            }
        }
        
        public string preset {
            get {
                return _preset;
            }
            set {
                _preset = value;
            }
        }
        
        public bool isReadable {
            get {
                return _isreadable;
            }
            set {
                _isreadable = value;
            }
        }
        
        public Shader_Wrapper shader {
            get {
                return this._shader;
            }
            set {
                this._shader = value;
            }
        }
        
        public Color_Wrapper color {
            get {
                return this._color;
            }
            set {
                this._color = value;
            }
        }
        
        public Texture_Wrapper mainTexture {
            get {
                return this._maintexture;
            }
            set {
                this._maintexture = value;
            }
        }
        
        public Vector2_Wrapper mainTextureOffset {
            get {
                return this._maintextureoffset;
            }
            set {
                this._maintextureoffset = value;
            }
        }
        
        public Vector2_Wrapper mainTextureScale {
            get {
                return this._maintexturescale;
            }
            set {
                this._maintexturescale = value;
            }
        }
        
        public int passCount {
            get {
                return _passcount;
            }
            set {
                _passcount = value;
            }
        }
        
        public int renderQueue {
            get {
                return _renderqueue;
            }
            set {
                _renderqueue = value;
            }
        }
        
        public string[] shaderKeywords {
            get {
                return _shaderkeywords;
            }
            set {
                _shaderkeywords = value;
            }
        }
        
        public string name {
            get {
                return _name;
            }
            set {
                _name = value;
            }
        }
        
        public UnityEngine.HideFlags hideFlags {
            get {
                return _hideflags;
            }
            set {
                _hideflags = value;
            }
        }
    }
}
