//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class ProtoPart_Wrapper {
        
        public string partName;
        
        public uint uid;
        
        public Vector3_Wrapper position;
        
        public Quaternion_Wrapper rotation;
        
        public Quaternion_Wrapper attRotation;
        
        public Vector3_Wrapper mirror;
        
        public AvailablePart partInfo;
        
        public System.Collections.Generic.List<ProtoPart> links;
        
        public System.Collections.Generic.List<ProtoPart> symmetryCounterparts;
        
        public System.Collections.Generic.List<ProtoAttachNode> attachNodes;
        
        public ProtoAttachNode_Wrapper srfAttachNode;
        
        public System.Collections.Generic.List<ProtoPartModuleSnapshot> protoModules;
        
        public Part_Wrapper newPart;
        
        public int inverseStageIndex;
        
        public int defaultInverseStage;
        
        public int seqOverride;
        
        public int inStageIndex;
        
        public string customPartData;
        
        public int attachMode;
    }
}
