//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Quaternion_Wrapper {
        
        public float _kEpsilon_wrapped;
        
        private float _item;
        
        private Vector3_Wrapper _eulerangles;
        
        public float Item {
            get {
                return _item;
            }
            set {
                _item = value;
            }
        }
        
        public Vector3_Wrapper eulerAngles {
            get {
                return this._eulerangles;
            }
            set {
                this._eulerangles = value;
            }
        }
    }
}
