//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    [SocketCommon.Attributes.InstanceNameAttribute("identity")]
    public class Quaternion_Wrapper {
        
        public float x;
        
        public float y;
        
        public float z;
        
        public float w;
        
        public float kEpsilon;
        
        public float Item;
        
        public Quaternion_Wrapper identity;
        
        public Vector3_Wrapper eulerAngles;
    }
}
