//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Random_Wrapper {
        
        public int seed;
        
        public float value;
        
        public Vector3_Wrapper insideUnitSphere;
        
        public Vector2_Wrapper insideUnitCircle;
        
        public Vector3_Wrapper onUnitSphere;
        
        public Quaternion_Wrapper rotation;
        
        public Quaternion_Wrapper rotationUniform;
    }
}
