//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Ray2D_Wrapper {
        
        private Vector2_Wrapper _origin;
        
        private Vector2_Wrapper _direction;
        
        public Vector2_Wrapper origin {
            get {
                return this._origin;
            }
            set {
                this._origin = value;
            }
        }
        
        public Vector2_Wrapper direction {
            get {
                return this._direction;
            }
            set {
                this._direction = value;
            }
        }
    }
}
