//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    [SocketCommon.Attributes.InstanceNameAttribute("active")]
    public class RenderTexture_Wrapper {
        
        public int width;
        
        public int height;
        
        public int depth;
        
        public bool isPowerOfTwo;
        
        public bool sRGB;
        
        public UnityEngine.RenderTextureFormat format;
        
        public bool useMipMap;
        
        public bool generateMips;
        
        public bool isCubemap;
        
        public bool isVolume;
        
        public int volumeDepth;
        
        public int antiAliasing;
        
        public bool enableRandomWrite;
        
        public RenderBuffer_Wrapper colorBuffer;
        
        public RenderBuffer_Wrapper depthBuffer;
        
        public RenderTexture_Wrapper active;
        
        public bool enabled;
        
        public UnityEngine.FilterMode filterMode;
        
        public int anisoLevel;
        
        public UnityEngine.TextureWrapMode wrapMode;
        
        public float mipMapBias;
        
        public Vector2_Wrapper texelSize;
        
        public string name;
        
        public UnityEngine.HideFlags hideFlags;
    }
}
