//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    [SocketCommon.Attributes.InstanceNameAttribute("rigidbody2D")]
    public class Rigidbody2D_Wrapper {
        
        public Vector2_Wrapper position;
        
        public float rotation;
        
        public Vector2_Wrapper velocity;
        
        public float angularVelocity;
        
        public float mass;
        
        public Vector2_Wrapper centerOfMass;
        
        public Vector2_Wrapper worldCenterOfMass;
        
        public float inertia;
        
        public float drag;
        
        public float angularDrag;
        
        public float gravityScale;
        
        public bool isKinematic;
        
        public bool fixedAngle;
        
        public bool simulated;
        
        public UnityEngine.RigidbodyInterpolation2D interpolation;
        
        public UnityEngine.RigidbodySleepMode2D sleepMode;
        
        public UnityEngine.CollisionDetectionMode2D collisionDetectionMode;
        
        public Transform_Wrapper transform;
        
        public Rigidbody_Wrapper rigidbody;
        
        public Rigidbody2D_Wrapper rigidbody2D;
        
        public Camera_Wrapper camera;
        
        public Light_Wrapper light;
        
        public Animation_Wrapper animation;
        
        public ConstantForce_Wrapper constantForce;
        
        public Renderer_Wrapper renderer;
        
        public AudioSource_Wrapper audio;
        
        public GUIText_Wrapper guiText;
        
        public NetworkView_Wrapper networkView;
        
        public GUIElement_Wrapper guiElement;
        
        public GUITexture_Wrapper guiTexture;
        
        public Collider_Wrapper collider;
        
        public Collider2D_Wrapper collider2D;
        
        public HingeJoint_Wrapper hingeJoint;
        
        public ParticleEmitter_Wrapper particleEmitter;
        
        public ParticleSystem_Wrapper particleSystem;
        
        public GameObject_Wrapper gameObject;
        
        public bool active;
        
        public string tag;
        
        public string name;
        
        public UnityEngine.HideFlags hideFlags;
    }
}
