//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Score_Wrapper {
        
        public string leaderboardID;
        
        public long value;
        
        public System.DateTime date;
        
        public string formattedValue;
        
        public string userID;
        
        public int rank;
    }
}
