//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Score_Wrapper {
        
        private string _leaderboardid;
        
        private long _value;
        
        private System.DateTime _date;
        
        private string _formattedvalue;
        
        private string _userid;
        
        private int _rank;
        
        public string leaderboardID {
            get {
                return _leaderboardid;
            }
            set {
                _leaderboardid = value;
            }
        }
        
        public long value {
            get {
                return _value;
            }
            set {
                _value = value;
            }
        }
        
        public System.DateTime date {
            get {
                return _date;
            }
            set {
                _date = value;
            }
        }
        
        public string formattedValue {
            get {
                return _formattedvalue;
            }
            set {
                _formattedvalue = value;
            }
        }
        
        public string userID {
            get {
                return _userid;
            }
            set {
                _userid = value;
            }
        }
        
        public int rank {
            get {
                return _rank;
            }
            set {
                _rank = value;
            }
        }
    }
}
