//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class SGT_Planet_Wrapper {
        
        public GameObject_Wrapper LightSource;
        
        public Mesh_Wrapper SurfaceMesh;
        
        public Texture2D_Wrapper SurfaceDayTexture;
        
        public Texture2D_Wrapper SurfaceNightTexture;
        
        public Texture2D_Wrapper SurfaceNormalTexture;
        
        public Texture2D_Wrapper SurfaceSpecularTexture;
        
        public bool HasShadow;
        
        public bool ShadowManualUpdate;
        
        public SGT.ShadowOccluderType ShadowType;
        
        public Texture2D_Wrapper SurfaceShadowTexture;
        
        public Texture2D_Wrapper AtmosphereShadowTexture;
        
        public Texture2D_Wrapper CloudsShadowTexture;
        
        public GameObject_Wrapper ShadowGameObject;
        
        public float ShadowRadius;
        
        public float ShadowRadiusOuter;
        
        public float ShadowWidth;
        
        public float SurfaceSpecularPower;
        
        public SGT.ColourGradient SurfaceLighting;
        
        public SGT.ColourGradient AtmosphereTwilightColour;
        
        public float AtmosphereNightOpacity;
        
        public float SurfaceRadius;
        
        public float SurfaceRotationPeriod;
        
        public bool HasClouds;
        
        public Mesh_Wrapper CloudsMesh;
        
        public Texture_Wrapper CloudsTexture;
        
        public float CloudsHeight;
        
        public float CloudsFalloff;
        
        public float CloudsOffset;
        
        public float CloudsRotationPeriod;
        
        public float CloudsTwilightOffset;
        
        public SGT.ColourGradient CloudsLimbColour;
        
        public bool HasAtmosphere;
        
        public bool AtmosphereSurfacePerPixel;
        
        public bool AtmosphereScattering;
        
        public float AtmosphereScatteringMie;
        
        public float AtmosphereScatteringRayleigh;
        
        public Mesh_Wrapper AtmosphereMesh;
        
        public float AtmosphereHeight;
        
        public float AtmosphereFalloff;
        
        public float AtmosphereSurfaceFalloff;
        
        public float AtmosphereSkyFalloff;
        
        public float AtmosphereSkyAltitude;
        
        public SGT.ColourGradient AtmosphereDensityColour;
        
        public float AtmosphereRadius;
        
        public float CloudsRadius;
        
        public bool InsideAtmosphere;
        
        public Vector3_Wrapper LightSourceDirection;
        
        public int SurfaceRenderQueue;
        
        public int AtmosphereRenderQueue;
        
        public Camera_Wrapper Observer;
        
        public UnityEngine.Object[] UndoTargets;
        
        public float UniformScale;
        
        public bool useGUILayout;
        
        public bool enabled;
        
        public Transform_Wrapper transform;
        
        public Rigidbody_Wrapper rigidbody;
        
        public Rigidbody2D_Wrapper rigidbody2D;
        
        public Camera_Wrapper camera;
        
        public Light_Wrapper light;
        
        public Animation_Wrapper animation;
        
        public ConstantForce_Wrapper constantForce;
        
        public Renderer_Wrapper renderer;
        
        public AudioSource_Wrapper audio;
        
        public GUIText_Wrapper guiText;
        
        public NetworkView_Wrapper networkView;
        
        public GUIElement_Wrapper guiElement;
        
        public GUITexture_Wrapper guiTexture;
        
        public Collider_Wrapper collider;
        
        public Collider2D_Wrapper collider2D;
        
        public HingeJoint_Wrapper hingeJoint;
        
        public ParticleEmitter_Wrapper particleEmitter;
        
        public ParticleSystem_Wrapper particleSystem;
        
        public GameObject_Wrapper gameObject;
        
        public bool active;
        
        public string tag;
        
        public string name;
        
        public UnityEngine.HideFlags hideFlags;
    }
}
