//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class SGT_Planet_Wrapper {
        
        private GameObject_Wrapper _lightsource;
        
        private Mesh_Wrapper _surfacemesh;
        
        private Texture2D_Wrapper _surfacedaytexture;
        
        private Texture2D_Wrapper _surfacenighttexture;
        
        private Texture2D_Wrapper _surfacenormaltexture;
        
        private Texture2D_Wrapper _surfacespeculartexture;
        
        private bool _hasshadow;
        
        private bool _shadowmanualupdate;
        
        private SGT.ShadowOccluderType _shadowtype;
        
        private Texture2D_Wrapper _surfaceshadowtexture;
        
        private Texture2D_Wrapper _atmosphereshadowtexture;
        
        private Texture2D_Wrapper _cloudsshadowtexture;
        
        private GameObject_Wrapper _shadowgameobject;
        
        private float _shadowradius;
        
        private float _shadowradiusouter;
        
        private float _shadowwidth;
        
        private float _surfacespecularpower;
        
        private SGT.ColourGradient _surfacelighting;
        
        private SGT.ColourGradient _atmospheretwilightcolour;
        
        private float _atmospherenightopacity;
        
        private float _surfaceradius;
        
        private float _surfacerotationperiod;
        
        private bool _hasclouds;
        
        private Mesh_Wrapper _cloudsmesh;
        
        private Texture_Wrapper _cloudstexture;
        
        private float _cloudsheight;
        
        private float _cloudsfalloff;
        
        private float _cloudsoffset;
        
        private float _cloudsrotationperiod;
        
        private float _cloudstwilightoffset;
        
        private SGT.ColourGradient _cloudslimbcolour;
        
        private bool _hasatmosphere;
        
        private bool _atmospheresurfaceperpixel;
        
        private bool _atmospherescattering;
        
        private float _atmospherescatteringmie;
        
        private float _atmospherescatteringrayleigh;
        
        private Mesh_Wrapper _atmospheremesh;
        
        private float _atmosphereheight;
        
        private float _atmospherefalloff;
        
        private float _atmospheresurfacefalloff;
        
        private float _atmosphereskyfalloff;
        
        private float _atmosphereskyaltitude;
        
        private SGT.ColourGradient _atmospheredensitycolour;
        
        private float _atmosphereradius;
        
        private float _cloudsradius;
        
        private bool _insideatmosphere;
        
        private Vector3_Wrapper _lightsourcedirection;
        
        private int _surfacerenderqueue;
        
        private int _atmosphererenderqueue;
        
        private Camera_Wrapper _observer;
        
        private UnityEngine.Object[] _undotargets;
        
        private float _uniformscale;
        
        private bool _useguilayout;
        
        private bool _enabled;
        
        private Transform_Wrapper _transform;
        
        private Rigidbody_Wrapper _rigidbody;
        
        private Rigidbody2D_Wrapper _rigidbody2d;
        
        private Camera_Wrapper _camera;
        
        private Light_Wrapper _light;
        
        private Animation_Wrapper _animation;
        
        private ConstantForce_Wrapper _constantforce;
        
        private Renderer_Wrapper _renderer;
        
        private AudioSource_Wrapper _audio;
        
        private GUIText_Wrapper _guitext;
        
        private NetworkView_Wrapper _networkview;
        
        private GUIElement_Wrapper _guielement;
        
        private GUITexture_Wrapper _guitexture;
        
        private Collider_Wrapper _collider;
        
        private Collider2D_Wrapper _collider2d;
        
        private HingeJoint_Wrapper _hingejoint;
        
        private ParticleEmitter_Wrapper _particleemitter;
        
        private ParticleSystem_Wrapper _particlesystem;
        
        private GameObject_Wrapper _gameobject;
        
        private bool _active;
        
        private string _tag;
        
        private string _name;
        
        private UnityEngine.HideFlags _hideflags;
        
        public GameObject_Wrapper LightSource {
            get {
                return this._lightsource;
            }
            set {
                this._lightsource = value;
            }
        }
        
        public Mesh_Wrapper SurfaceMesh {
            get {
                return this._surfacemesh;
            }
            set {
                this._surfacemesh = value;
            }
        }
        
        public Texture2D_Wrapper SurfaceDayTexture {
            get {
                return this._surfacedaytexture;
            }
            set {
                this._surfacedaytexture = value;
            }
        }
        
        public Texture2D_Wrapper SurfaceNightTexture {
            get {
                return this._surfacenighttexture;
            }
            set {
                this._surfacenighttexture = value;
            }
        }
        
        public Texture2D_Wrapper SurfaceNormalTexture {
            get {
                return this._surfacenormaltexture;
            }
            set {
                this._surfacenormaltexture = value;
            }
        }
        
        public Texture2D_Wrapper SurfaceSpecularTexture {
            get {
                return this._surfacespeculartexture;
            }
            set {
                this._surfacespeculartexture = value;
            }
        }
        
        public bool HasShadow {
            get {
                return _hasshadow;
            }
            set {
                _hasshadow = value;
            }
        }
        
        public bool ShadowManualUpdate {
            get {
                return _shadowmanualupdate;
            }
            set {
                _shadowmanualupdate = value;
            }
        }
        
        public SGT.ShadowOccluderType ShadowType {
            get {
                return _shadowtype;
            }
            set {
                _shadowtype = value;
            }
        }
        
        public Texture2D_Wrapper SurfaceShadowTexture {
            get {
                return this._surfaceshadowtexture;
            }
            set {
                this._surfaceshadowtexture = value;
            }
        }
        
        public Texture2D_Wrapper AtmosphereShadowTexture {
            get {
                return this._atmosphereshadowtexture;
            }
            set {
                this._atmosphereshadowtexture = value;
            }
        }
        
        public Texture2D_Wrapper CloudsShadowTexture {
            get {
                return this._cloudsshadowtexture;
            }
            set {
                this._cloudsshadowtexture = value;
            }
        }
        
        public GameObject_Wrapper ShadowGameObject {
            get {
                return this._shadowgameobject;
            }
            set {
                this._shadowgameobject = value;
            }
        }
        
        public float ShadowRadius {
            get {
                return _shadowradius;
            }
            set {
                _shadowradius = value;
            }
        }
        
        public float ShadowRadiusOuter {
            get {
                return _shadowradiusouter;
            }
            set {
                _shadowradiusouter = value;
            }
        }
        
        public float ShadowWidth {
            get {
                return _shadowwidth;
            }
            set {
                _shadowwidth = value;
            }
        }
        
        public float SurfaceSpecularPower {
            get {
                return _surfacespecularpower;
            }
            set {
                _surfacespecularpower = value;
            }
        }
        
        public SGT.ColourGradient SurfaceLighting {
            get {
                return _surfacelighting;
            }
            set {
                _surfacelighting = value;
            }
        }
        
        public SGT.ColourGradient AtmosphereTwilightColour {
            get {
                return _atmospheretwilightcolour;
            }
            set {
                _atmospheretwilightcolour = value;
            }
        }
        
        public float AtmosphereNightOpacity {
            get {
                return _atmospherenightopacity;
            }
            set {
                _atmospherenightopacity = value;
            }
        }
        
        public float SurfaceRadius {
            get {
                return _surfaceradius;
            }
            set {
                _surfaceradius = value;
            }
        }
        
        public float SurfaceRotationPeriod {
            get {
                return _surfacerotationperiod;
            }
            set {
                _surfacerotationperiod = value;
            }
        }
        
        public bool HasClouds {
            get {
                return _hasclouds;
            }
            set {
                _hasclouds = value;
            }
        }
        
        public Mesh_Wrapper CloudsMesh {
            get {
                return this._cloudsmesh;
            }
            set {
                this._cloudsmesh = value;
            }
        }
        
        public Texture_Wrapper CloudsTexture {
            get {
                return this._cloudstexture;
            }
            set {
                this._cloudstexture = value;
            }
        }
        
        public float CloudsHeight {
            get {
                return _cloudsheight;
            }
            set {
                _cloudsheight = value;
            }
        }
        
        public float CloudsFalloff {
            get {
                return _cloudsfalloff;
            }
            set {
                _cloudsfalloff = value;
            }
        }
        
        public float CloudsOffset {
            get {
                return _cloudsoffset;
            }
            set {
                _cloudsoffset = value;
            }
        }
        
        public float CloudsRotationPeriod {
            get {
                return _cloudsrotationperiod;
            }
            set {
                _cloudsrotationperiod = value;
            }
        }
        
        public float CloudsTwilightOffset {
            get {
                return _cloudstwilightoffset;
            }
            set {
                _cloudstwilightoffset = value;
            }
        }
        
        public SGT.ColourGradient CloudsLimbColour {
            get {
                return _cloudslimbcolour;
            }
            set {
                _cloudslimbcolour = value;
            }
        }
        
        public bool HasAtmosphere {
            get {
                return _hasatmosphere;
            }
            set {
                _hasatmosphere = value;
            }
        }
        
        public bool AtmosphereSurfacePerPixel {
            get {
                return _atmospheresurfaceperpixel;
            }
            set {
                _atmospheresurfaceperpixel = value;
            }
        }
        
        public bool AtmosphereScattering {
            get {
                return _atmospherescattering;
            }
            set {
                _atmospherescattering = value;
            }
        }
        
        public float AtmosphereScatteringMie {
            get {
                return _atmospherescatteringmie;
            }
            set {
                _atmospherescatteringmie = value;
            }
        }
        
        public float AtmosphereScatteringRayleigh {
            get {
                return _atmospherescatteringrayleigh;
            }
            set {
                _atmospherescatteringrayleigh = value;
            }
        }
        
        public Mesh_Wrapper AtmosphereMesh {
            get {
                return this._atmospheremesh;
            }
            set {
                this._atmospheremesh = value;
            }
        }
        
        public float AtmosphereHeight {
            get {
                return _atmosphereheight;
            }
            set {
                _atmosphereheight = value;
            }
        }
        
        public float AtmosphereFalloff {
            get {
                return _atmospherefalloff;
            }
            set {
                _atmospherefalloff = value;
            }
        }
        
        public float AtmosphereSurfaceFalloff {
            get {
                return _atmospheresurfacefalloff;
            }
            set {
                _atmospheresurfacefalloff = value;
            }
        }
        
        public float AtmosphereSkyFalloff {
            get {
                return _atmosphereskyfalloff;
            }
            set {
                _atmosphereskyfalloff = value;
            }
        }
        
        public float AtmosphereSkyAltitude {
            get {
                return _atmosphereskyaltitude;
            }
            set {
                _atmosphereskyaltitude = value;
            }
        }
        
        public SGT.ColourGradient AtmosphereDensityColour {
            get {
                return _atmospheredensitycolour;
            }
            set {
                _atmospheredensitycolour = value;
            }
        }
        
        public float AtmosphereRadius {
            get {
                return _atmosphereradius;
            }
            set {
                _atmosphereradius = value;
            }
        }
        
        public float CloudsRadius {
            get {
                return _cloudsradius;
            }
            set {
                _cloudsradius = value;
            }
        }
        
        public bool InsideAtmosphere {
            get {
                return _insideatmosphere;
            }
            set {
                _insideatmosphere = value;
            }
        }
        
        public Vector3_Wrapper LightSourceDirection {
            get {
                return this._lightsourcedirection;
            }
            set {
                this._lightsourcedirection = value;
            }
        }
        
        public int SurfaceRenderQueue {
            get {
                return _surfacerenderqueue;
            }
            set {
                _surfacerenderqueue = value;
            }
        }
        
        public int AtmosphereRenderQueue {
            get {
                return _atmosphererenderqueue;
            }
            set {
                _atmosphererenderqueue = value;
            }
        }
        
        public Camera_Wrapper Observer {
            get {
                return this._observer;
            }
            set {
                this._observer = value;
            }
        }
        
        public UnityEngine.Object[] UndoTargets {
            get {
                return _undotargets;
            }
            set {
                _undotargets = value;
            }
        }
        
        public float UniformScale {
            get {
                return _uniformscale;
            }
            set {
                _uniformscale = value;
            }
        }
        
        public bool useGUILayout {
            get {
                return _useguilayout;
            }
            set {
                _useguilayout = value;
            }
        }
        
        public bool enabled {
            get {
                return _enabled;
            }
            set {
                _enabled = value;
            }
        }
        
        public Transform_Wrapper transform {
            get {
                return this._transform;
            }
            set {
                this._transform = value;
            }
        }
        
        public Rigidbody_Wrapper rigidbody {
            get {
                return this._rigidbody;
            }
            set {
                this._rigidbody = value;
            }
        }
        
        public Rigidbody2D_Wrapper rigidbody2D {
            get {
                return this._rigidbody2d;
            }
            set {
                this._rigidbody2d = value;
            }
        }
        
        public Camera_Wrapper camera {
            get {
                return this._camera;
            }
            set {
                this._camera = value;
            }
        }
        
        public Light_Wrapper light {
            get {
                return this._light;
            }
            set {
                this._light = value;
            }
        }
        
        public Animation_Wrapper animation {
            get {
                return this._animation;
            }
            set {
                this._animation = value;
            }
        }
        
        public ConstantForce_Wrapper constantForce {
            get {
                return this._constantforce;
            }
            set {
                this._constantforce = value;
            }
        }
        
        public Renderer_Wrapper renderer {
            get {
                return this._renderer;
            }
            set {
                this._renderer = value;
            }
        }
        
        public AudioSource_Wrapper audio {
            get {
                return this._audio;
            }
            set {
                this._audio = value;
            }
        }
        
        public GUIText_Wrapper guiText {
            get {
                return this._guitext;
            }
            set {
                this._guitext = value;
            }
        }
        
        public NetworkView_Wrapper networkView {
            get {
                return this._networkview;
            }
            set {
                this._networkview = value;
            }
        }
        
        public GUIElement_Wrapper guiElement {
            get {
                return this._guielement;
            }
            set {
                this._guielement = value;
            }
        }
        
        public GUITexture_Wrapper guiTexture {
            get {
                return this._guitexture;
            }
            set {
                this._guitexture = value;
            }
        }
        
        public Collider_Wrapper collider {
            get {
                return this._collider;
            }
            set {
                this._collider = value;
            }
        }
        
        public Collider2D_Wrapper collider2D {
            get {
                return this._collider2d;
            }
            set {
                this._collider2d = value;
            }
        }
        
        public HingeJoint_Wrapper hingeJoint {
            get {
                return this._hingejoint;
            }
            set {
                this._hingejoint = value;
            }
        }
        
        public ParticleEmitter_Wrapper particleEmitter {
            get {
                return this._particleemitter;
            }
            set {
                this._particleemitter = value;
            }
        }
        
        public ParticleSystem_Wrapper particleSystem {
            get {
                return this._particlesystem;
            }
            set {
                this._particlesystem = value;
            }
        }
        
        public GameObject_Wrapper gameObject {
            get {
                return this._gameobject;
            }
            set {
                this._gameobject = value;
            }
        }
        
        public bool active {
            get {
                return _active;
            }
            set {
                _active = value;
            }
        }
        
        public string tag {
            get {
                return _tag;
            }
            set {
                _tag = value;
            }
        }
        
        public string name {
            get {
                return _name;
            }
            set {
                _name = value;
            }
        }
        
        public UnityEngine.HideFlags hideFlags {
            get {
                return _hideflags;
            }
            set {
                _hideflags = value;
            }
        }
    }
}
