//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class SparseTexture_Wrapper {
        
        private int _tilewidth;
        
        private int _tileheight;
        
        private bool _iscreated;
        
        private int _width;
        
        private int _height;
        
        private UnityEngine.FilterMode _filtermode;
        
        private int _anisolevel;
        
        private UnityEngine.TextureWrapMode _wrapmode;
        
        private float _mipmapbias;
        
        private Vector2_Wrapper _texelsize;
        
        private string _name;
        
        private UnityEngine.HideFlags _hideflags;
        
        public int tileWidth {
            get {
                return _tilewidth;
            }
            set {
                _tilewidth = value;
            }
        }
        
        public int tileHeight {
            get {
                return _tileheight;
            }
            set {
                _tileheight = value;
            }
        }
        
        public bool isCreated {
            get {
                return _iscreated;
            }
            set {
                _iscreated = value;
            }
        }
        
        public int width {
            get {
                return _width;
            }
            set {
                _width = value;
            }
        }
        
        public int height {
            get {
                return _height;
            }
            set {
                _height = value;
            }
        }
        
        public UnityEngine.FilterMode filterMode {
            get {
                return _filtermode;
            }
            set {
                _filtermode = value;
            }
        }
        
        public int anisoLevel {
            get {
                return _anisolevel;
            }
            set {
                _anisolevel = value;
            }
        }
        
        public UnityEngine.TextureWrapMode wrapMode {
            get {
                return _wrapmode;
            }
            set {
                _wrapmode = value;
            }
        }
        
        public float mipMapBias {
            get {
                return _mipmapbias;
            }
            set {
                _mipmapbias = value;
            }
        }
        
        public Vector2_Wrapper texelSize {
            get {
                return this._texelsize;
            }
            set {
                this._texelsize = value;
            }
        }
        
        public string name {
            get {
                return _name;
            }
            set {
                _name = value;
            }
        }
        
        public UnityEngine.HideFlags hideFlags {
            get {
                return _hideflags;
            }
            set {
                _hideflags = value;
            }
        }
    }
}
