//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class SplatPrototype_Wrapper {
        
        public Texture2D_Wrapper texture;
        
        public Texture2D_Wrapper normalMap;
        
        public Vector2_Wrapper tileSize;
        
        public Vector2_Wrapper tileOffset;
    }
}
