//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Staging_Wrapper {
        
        public System.Collections.Generic.List<StageGroup> stages;
        
        public System.Collections.Generic.List<StackIcon> iconsInHold;
        
        public System.Collections.Generic.List<StackIcon> frozenIcons;
        
        public System.Collections.Generic.List<StackIcon> selection;
        
        public float stageSpacing;
        
        public float iconSpacing;
        
        public Vector3_Wrapper iconOffset;
        
        public Vector3_Wrapper iconHoldingArea;
        
        public Vector3_Wrapper iconFrozenArea;
        
        public BoxCollider_Wrapper hoverArea;
        
        public float scrollSharpness;
        
        public float scrollTop;
        
        public StageGroup_Wrapper indicatorPrefab;
        
        public ScreenSafeUIButton_Wrapper resetButton;
        
        public Texture2D_Wrapper defaultIconMapTexture;
        
        public float separate_cooldown;
        
        public AudioClip_Wrapper cannotSeparateClip;
        
        public AudioClip_Wrapper nextStageClip;
        
        public bool advancedStagingControls;
        
        public bool hover;
        
        public bool stackMoving;
        
        public System.Collections.Generic.List<StackIcon> Selection;
        
        public float IconSpacing;
        
        public Vector3_Wrapper IconOffset;
        
        public Transform_Wrapper StackTransform;
        
        public bool stackLocked;
        
        public Texture2D_Wrapper DefaultIconMapTexture;
        
        public int lastStage;
        
        public int StageCount;
        
        public int CurrentStage;
        
        public bool separate_ready;
        
        public bool AdvancedStagingControls;
        
        public bool useGUILayout;
        
        public bool enabled;
        
        public Transform_Wrapper transform;
        
        public Rigidbody_Wrapper rigidbody;
        
        public Rigidbody2D_Wrapper rigidbody2D;
        
        public Camera_Wrapper camera;
        
        public Light_Wrapper light;
        
        public Animation_Wrapper animation;
        
        public ConstantForce_Wrapper constantForce;
        
        public Renderer_Wrapper renderer;
        
        public AudioSource_Wrapper audio;
        
        public GUIText_Wrapper guiText;
        
        public NetworkView_Wrapper networkView;
        
        public GUIElement_Wrapper guiElement;
        
        public GUITexture_Wrapper guiTexture;
        
        public Collider_Wrapper collider;
        
        public Collider2D_Wrapper collider2D;
        
        public HingeJoint_Wrapper hingeJoint;
        
        public ParticleEmitter_Wrapper particleEmitter;
        
        public ParticleSystem_Wrapper particleSystem;
        
        public GameObject_Wrapper gameObject;
        
        public bool active;
        
        public string tag;
        
        public string name;
        
        public UnityEngine.HideFlags hideFlags;
    }
}
