//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class TextReader_Wrapper {
        
        public System.Text.Encoding CurrentEncoding;
        
        public System.IO.Stream BaseStream;
        
        public bool EndOfStream;
    }
}
