//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    [SocketCommon.Attributes.InstanceNameAttribute("CurrentThread")]
    public class ThreadBase_Wrapper {
        
        public ThreadBase_Wrapper CurrentThread;
        
        public bool IsAlive;
        
        public bool ShouldStop;
    }
}
