//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Touch_Wrapper {
        
        private int _fingerid;
        
        private Vector2_Wrapper _position;
        
        private Vector2_Wrapper _rawposition;
        
        private Vector2_Wrapper _deltaposition;
        
        private float _deltatime;
        
        private int _tapcount;
        
        private UnityEngine.TouchPhase _phase;
        
        public int fingerId {
            get {
                return _fingerid;
            }
            set {
                _fingerid = value;
            }
        }
        
        public Vector2_Wrapper position {
            get {
                return this._position;
            }
            set {
                this._position = value;
            }
        }
        
        public Vector2_Wrapper rawPosition {
            get {
                return this._rawposition;
            }
            set {
                this._rawposition = value;
            }
        }
        
        public Vector2_Wrapper deltaPosition {
            get {
                return this._deltaposition;
            }
            set {
                this._deltaposition = value;
            }
        }
        
        public float deltaTime {
            get {
                return _deltatime;
            }
            set {
                _deltatime = value;
            }
        }
        
        public int tapCount {
            get {
                return _tapcount;
            }
            set {
                _tapcount = value;
            }
        }
        
        public UnityEngine.TouchPhase phase {
            get {
                return _phase;
            }
            set {
                _phase = value;
            }
        }
    }
}
