//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class UI_Label_Wrapper {
        
        private object _typeid;
        
        public object TypeId {
            get {
                return _typeid;
            }
            set {
                _typeid = value;
            }
        }
    }
}
