//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class UI_Vector2_Wrapper {
        
        public float minValueX;
        
        public float maxValueX;
        
        public float minValueY;
        
        public float maxValueY;
        
        public UI_Scene scene;
        
        public bool controlEnabled;
        
        public object TypeId;
    }
}
