//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class UnityLogWriter_Wrapper {
        
        private System.Text.Encoding _encoding;
        
        private System.IFormatProvider _formatprovider;
        
        private string _newline;
        
        public System.Text.Encoding Encoding {
            get {
                return _encoding;
            }
            set {
                _encoding = value;
            }
        }
        
        public System.IFormatProvider FormatProvider {
            get {
                return _formatprovider;
            }
            set {
                _formatprovider = value;
            }
        }
        
        public string NewLine {
            get {
                return _newline;
            }
            set {
                _newline = value;
            }
        }
    }
}
