//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class UrlDir_Wrapper {
        
        public string configExtension;
        
        public string name;
        
        public UrlDir_Wrapper root;
        
        public UrlDir_Wrapper parent;
        
        public System.Collections.Generic.List<UrlDir> children;
        
        public System.Collections.Generic.List<UrlDir.UrlFile> files;
        
        public string path;
        
        public UrlDir.DirectoryType type;
        
        public string url;
        
        public System.Collections.Generic.IEnumerable<UrlDir> AllDirectories;
        
        public System.Collections.Generic.IEnumerable<UrlDir.UrlFile> AllFiles;
        
        public System.Collections.Generic.IEnumerable<UrlDir.UrlFile> AllConfigFiles;
        
        public System.Collections.Generic.IEnumerable<UrlDir.UrlConfig> AllConfigs;
        
        public string ApplicationRootPath;
    }
}
