//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Vector4_Wrapper {
        
        public float x;
        
        public float y;
        
        public float z;
        
        public float w;
        
        public float kEpsilon;
        
        public float Item;
        
        public Vector4_Wrapper normalized;
        
        public float magnitude;
        
        public float sqrMagnitude;
        
        public Vector4_Wrapper zero;
        
        public Vector4_Wrapper one;
    }
}
