//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Vector3d_Wrapper {
        
        public double x;
        
        public double y;
        
        public double z;
        
        public float kEpsilon;
        
        public Vector3d_Wrapper xzy;
        
        public double Item;
        
        public Vector3d_Wrapper normalized;
        
        public double magnitude;
        
        public double sqrMagnitude;
        
        public Vector3d_Wrapper zero;
        
        public Vector3d_Wrapper one;
        
        public Vector3d_Wrapper forward;
        
        public Vector3d_Wrapper back;
        
        public Vector3d_Wrapper up;
        
        public Vector3d_Wrapper down;
        
        public Vector3d_Wrapper left;
        
        public Vector3d_Wrapper right;
        
        public Vector3d_Wrapper fwd;
    }
}
