//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class VesselRef_Wrapper {
        
        private string _name;
        
        private string _flagurl;
        
        public string Name {
            get {
                return _name;
            }
            set {
                _name = value;
            }
        }
        
        public string FlagURL {
            get {
                return _flagurl;
            }
            set {
                _flagurl = value;
            }
        }
    }
}
