//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class Voronoi_Wrapper {
        
        private double _displacement;
        
        private double _frequency;
        
        private int _seed;
        
        private bool _usedistance;
        
        private ModuleBase_Wrapper _item;
        
        private int _sourcemodulecount;
        
        private bool _isdisposed;
        
        public double Displacement {
            get {
                return _displacement;
            }
            set {
                _displacement = value;
            }
        }
        
        public double Frequency {
            get {
                return _frequency;
            }
            set {
                _frequency = value;
            }
        }
        
        public int Seed {
            get {
                return _seed;
            }
            set {
                _seed = value;
            }
        }
        
        public bool UseDistance {
            get {
                return _usedistance;
            }
            set {
                _usedistance = value;
            }
        }
        
        public ModuleBase_Wrapper Item {
            get {
                return this._item;
            }
            set {
                this._item = value;
            }
        }
        
        public int SourceModuleCount {
            get {
                return _sourcemodulecount;
            }
            set {
                _sourcemodulecount = value;
            }
        }
        
        public bool IsDisposed {
            get {
                return _isdisposed;
            }
            set {
                _isdisposed = value;
            }
        }
    }
}
