//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class VStackIcon_Wrapper {
        
        public DefaultIcons iconImage;
        
        public Color_Wrapper iconColor;
        
        public Color_Wrapper bgColor;
        
        public Color_Wrapper borderColor;
        
        public bool blinkBorder;
        
        public float blinkInterval;
        
        public bool frozen;
        
        public Vector3_Wrapper tgtPosition;
        
        public float moveDelay;
        
        public bool highlightIcon;
        
        public Part_Wrapper partRef;
        
        public Vector3_Wrapper homePos;
    }
}
