//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class VStackIcon_Wrapper {
        
        private Vector3_Wrapper _homepos;
        
        public Vector3_Wrapper homePos {
            get {
                return this._homepos;
            }
            set {
                this._homepos = value;
            }
        }
    }
}
