//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class WheelHit_Wrapper {
        
        private Collider_Wrapper _collider;
        
        private Vector3_Wrapper _point;
        
        private Vector3_Wrapper _normal;
        
        private Vector3_Wrapper _forwarddir;
        
        private Vector3_Wrapper _sidewaysdir;
        
        private float _force;
        
        private float _forwardslip;
        
        private float _sidewaysslip;
        
        public Collider_Wrapper collider {
            get {
                return this._collider;
            }
            set {
                this._collider = value;
            }
        }
        
        public Vector3_Wrapper point {
            get {
                return this._point;
            }
            set {
                this._point = value;
            }
        }
        
        public Vector3_Wrapper normal {
            get {
                return this._normal;
            }
            set {
                this._normal = value;
            }
        }
        
        public Vector3_Wrapper forwardDir {
            get {
                return this._forwarddir;
            }
            set {
                this._forwarddir = value;
            }
        }
        
        public Vector3_Wrapper sidewaysDir {
            get {
                return this._sidewaysdir;
            }
            set {
                this._sidewaysdir = value;
            }
        }
        
        public float force {
            get {
                return _force;
            }
            set {
                _force = value;
            }
        }
        
        public float forwardSlip {
            get {
                return _forwardslip;
            }
            set {
                _forwardslip = value;
            }
        }
        
        public float sidewaysSlip {
            get {
                return _sidewaysslip;
            }
            set {
                _sidewaysslip = value;
            }
        }
    }
}
