//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class WheelFrictionCurve_Wrapper {
        
        public float extremumSlip;
        
        public float extremumValue;
        
        public float asymptoteSlip;
        
        public float asymptoteValue;
        
        public float stiffness;
    }
}
