//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappers {
    
    
    [System.SerializableAttribute()]
    public class WWWForm_Wrapper {
        
        private System.Collections.Hashtable _headers;
        
        private byte[] _data;
        
        public System.Collections.Hashtable headers {
            get {
                return _headers;
            }
            set {
                _headers = value;
            }
        }
        
        public byte[] data {
            get {
                return _data;
            }
            set {
                _data = value;
            }
        }
    }
}
